// Auto-generated from data/quotes.json — do not edit by hand.
// Edit data/quotes.json then run: node -e "require('fs').writeFileSync('quotes.js', 'module.exports = ' + require('fs').readFileSync('data/quotes.json','utf8').trim() + ';\n')"
module.exports = {
  "_meta": {
    "version": 1,
    "sources": ["yoga_sutra", "bhagavad_gita", "hatha_yoga_pradipika", "stoic"],
    "per_source_target": 40,
    "languages": ["en", "ru", "zh"],
    "notes": "Curated for AYBKK student share cards. Quotes selected for depth and applicability to practice, not surface inspiration. Stoic = Marcus Aurelius, Epictetus, Seneca only."
  },
  "en": {
    "yoga_sutra": [
      "Atha Yoganushasanam — now, the teaching of yoga begins. — Yoga Sutra 1.1",
      "Yoga is the cessation of the fluctuations of the mind. — Yoga Sutra 1.2",
      "Then the seer abides in their true nature. — Yoga Sutra 1.3",
      "At other times, the seer takes the form of the fluctuations. — Yoga Sutra 1.4",
      "Practice and non-attachment are the means to still the movements of consciousness. — Yoga Sutra 1.12",
      "Practice is the steady effort to remain there. — Yoga Sutra 1.13",
      "Practice becomes firmly grounded when attended to for a long time, without break, with sincere devotion. — Yoga Sutra 1.14",
      "Maitri karuna mudita upekshanam — friendliness, compassion, gladness, equanimity. — Yoga Sutra 1.33",
      "When disturbed by negative thoughts, cultivate the opposite. — Yoga Sutra 2.33",
      "The cause of suffering that is to come is to be avoided. — Yoga Sutra 2.16",
      "Ignorance is mistaking the impermanent for the permanent, the impure for the pure, suffering for happiness, the non-Self for the Self. — Yoga Sutra 2.5",
      "Asana is steady and comfortable. — Yoga Sutra 2.46",
      "By relaxing effort and meditating on the infinite, asana is mastered. — Yoga Sutra 2.47",
      "Then the practitioner is no longer disturbed by the pairs of opposites. — Yoga Sutra 2.48",
      "Pranayama is the conscious cessation of the movement of inhalation and exhalation. — Yoga Sutra 2.49",
      "Then the covering of the inner light dissolves. — Yoga Sutra 2.52",
      "And the mind becomes fit for concentration. — Yoga Sutra 2.53",
      "Withdrawal of the senses is when they disengage from their objects. — Yoga Sutra 2.54",
      "From this comes supreme mastery over the senses. — Yoga Sutra 2.55",
      "Concentration is the binding of consciousness to a single point. — Yoga Sutra 3.1",
      "Meditation is the unbroken flow of consciousness toward that point. — Yoga Sutra 3.2",
      "Samadhi is when the object alone shines forth, as if the self were absent. — Yoga Sutra 3.3",
      "These three together are samyama. — Yoga Sutra 3.4",
      "Heyam dukham anagatam — the pain that has not yet come can be avoided. — Yoga Sutra 2.16",
      "Posture, breath, and the senses, mastered, prepare the mind for what cannot be reached by force. — Yoga Sutra 2.46–2.55",
      "Tapas, svadhyaya, ishvara-pranidhana — discipline, self-study, surrender — this is kriya yoga. — Yoga Sutra 2.1",
      "By kriya yoga, afflictions are weakened and samadhi cultivated. — Yoga Sutra 2.2",
      "The five afflictions are: ignorance, ego, attachment, aversion, clinging to life. — Yoga Sutra 2.3",
      "Ignorance is the field for the others. — Yoga Sutra 2.4",
      "When right knowledge arises, the cause of suffering ends. — Yoga Sutra 2.25",
      "Yamas: non-violence, truth, non-stealing, continence, non-grasping. — Yoga Sutra 2.30",
      "These yamas are the great vow, valid in all places, all times, all conditions. — Yoga Sutra 2.31",
      "Niyamas: purity, contentment, discipline, self-study, surrender. — Yoga Sutra 2.32",
      "When non-violence is established, hostility ceases in the practitioner's presence. — Yoga Sutra 2.35",
      "When truth is established, words become fruitful. — Yoga Sutra 2.36",
      "From contentment comes unsurpassed happiness. — Yoga Sutra 2.42",
      "From self-study, communion with the chosen ideal. — Yoga Sutra 2.44",
      "From surrender to the Lord, samadhi is attained. — Yoga Sutra 2.45",
      "Right knowledge, error, imagination, sleep, and memory are the five fluctuations. — Yoga Sutra 1.6",
      "Cessation of these comes through practice and dispassion. — Yoga Sutra 1.12"
    ],
    "bhagavad_gita": [
      "You have a right to action, but never to its fruits. Let not the fruits of action be your motive, nor let your attachment be to inaction. — Bhagavad Gita 2.47",
      "Yoga is skill in action. — Bhagavad Gita 2.50",
      "Yoga is equanimity of mind. — Bhagavad Gita 2.48",
      "When meditation is mastered, the mind is unwavering — like a lamp in a windless place. — Bhagavad Gita 6.19",
      "For one who has conquered the mind, the mind is the best of friends; for one who has not, the mind remains the greatest enemy. — Bhagavad Gita 6.6",
      "The soul is neither born, nor does it die. — Bhagavad Gita 2.20",
      "Weapons cannot cleave it, fire cannot burn it, water cannot wet it, wind cannot dry it. — Bhagavad Gita 2.23",
      "Whoever sees inaction in action, and action in inaction, is wise among men. — Bhagavad Gita 4.18",
      "He who has no attachment, who is free, whose mind is established in knowledge — his work melts away. — Bhagavad Gita 4.23",
      "Better is one's own duty, though imperfectly performed, than the duty of another well-performed. — Bhagavad Gita 3.35",
      "Perform your duty, equipoised, abandoning attachment to success or failure. — Bhagavad Gita 2.48",
      "He who restrains the senses by the mind, without attachment, engages them in the path of action — he excels. — Bhagavad Gita 3.7",
      "From anger comes delusion; from delusion, loss of memory; from loss of memory, the destruction of intelligence; and from this, one perishes. — Bhagavad Gita 2.63",
      "When the senses move among objects with desire and aversion put aside, mastered by the self — one attains tranquility. — Bhagavad Gita 2.64",
      "In tranquility, all sorrows end; the intellect of the tranquil is soon firmly established. — Bhagavad Gita 2.65",
      "He whose mind is undisturbed in sorrow, free from desire in pleasure, free from passion, fear, and anger — is called a sage of steady wisdom. — Bhagavad Gita 2.56",
      "As the mighty wind sweeps away a boat upon the waters, so a single roving sense carries away the wisdom of one not in possession of himself. — Bhagavad Gita 2.67",
      "What is night for all beings is the time of waking for the disciplined; what is waking for all is night for the sage who sees. — Bhagavad Gita 2.69",
      "He attains peace into whom all desires enter as waters enter the ever-full ocean which remains unmoved. — Bhagavad Gita 2.70",
      "Yoga is not for one who eats too much, nor for one who eats too little; not for one who sleeps too much, nor for one who is always awake. — Bhagavad Gita 6.16",
      "Yoga becomes the destroyer of pain for one moderate in eating and recreation, balanced in action, balanced in sleep and waking. — Bhagavad Gita 6.17",
      "Lift yourself by yourself; do not let yourself be cast down. For the self alone is the friend of the self, and the self alone is the enemy of the self. — Bhagavad Gita 6.5",
      "Wherever the restless, unsteady mind wanders, restrain it and bring it back under the control of the Self. — Bhagavad Gita 6.26",
      "He who sees the Self in all beings and all beings in the Self — he never turns away from it. — Bhagavad Gita 6.30",
      "Among thousands of men, scarcely one strives for perfection; among those who strive, scarcely one knows me in truth. — Bhagavad Gita 7.3",
      "Whatever you do, whatever you eat, whatever you offer, whatever you give, whatever you practice — do that as an offering. — Bhagavad Gita 9.27",
      "I am time, the destroyer of worlds. — Bhagavad Gita 11.32",
      "He who has no ill will toward any being, who is friendly and compassionate — he is dear to me. — Bhagavad Gita 12.13",
      "Content with whatever comes, beyond the dualities, free from envy, balanced in success and failure — he is dear to me. — Bhagavad Gita 12.18",
      "He who endures cold and heat, joy and sorrow, with equanimity — is fit for immortality. — Bhagavad Gita 2.15",
      "The unreal has no being; the real never ceases to be. — Bhagavad Gita 2.16",
      "Just as a person puts on new garments, giving up old ones, the soul accepts new bodies, giving up the old. — Bhagavad Gita 2.22",
      "Faith makes a person what their faith is. — Bhagavad Gita 17.3",
      "He whose actions are free from the binding of desire, whose karma is burned in the fire of knowledge — the wise call him learned. — Bhagavad Gita 4.19",
      "Surrender all your duties to me; I will free you from all sins. Do not grieve. — Bhagavad Gita 18.66",
      "There is nothing in the three worlds I need to do, nor anything to attain — yet I act. — Bhagavad Gita 3.22",
      "Whatever a great man does, others follow. The standard he sets, the world pursues. — Bhagavad Gita 3.21",
      "Better is one's own dharma, even if imperfect, than the dharma of another, perfectly performed. — Bhagavad Gita 18.47",
      "He who has truly renounced is one who neither hates nor desires. — Bhagavad Gita 5.3",
      "The yogi who is harmonized in joy and sorrow, in honor and dishonor — he has gone beyond. — Bhagavad Gita 6.7"
    ],
    "hatha_yoga_pradipika": [
      "Salutation to Adinatha, who taught Hatha vidya as a stairway to the heights of Raja Yoga. — Hatha Yoga Pradipika 1.1",
      "Hatha Yoga is for those who are restless in Raja Yoga, a refuge for those overcome by the heat of the world. — Hatha Yoga Pradipika 1.10",
      "Yoga is destroyed by six causes: overeating, exertion, talkativeness, austerity, public contact, and unsteadiness. — Hatha Yoga Pradipika 1.15",
      "Yoga succeeds by six causes: enthusiasm, perseverance, discrimination, faith, courage, and avoiding the company of common people. — Hatha Yoga Pradipika 1.16",
      "Asana, being the first part of Hatha Yoga, is described first. It gives steadiness, health, and lightness of limb. — Hatha Yoga Pradipika 1.17",
      "By practicing it, the body becomes strong, the mind composed, and the disciple liberated from disease. — Hatha Yoga Pradipika 1.18",
      "Padmasana destroys all diseases of the practitioner. — Hatha Yoga Pradipika 1.47",
      "Such food as is sweet, fat, made of milk, nourishing the dhatus, agreeable and suitable — that the yogi should eat. — Hatha Yoga Pradipika 1.63",
      "When the breath wanders, the mind is unsteady. When the breath is still, so is the mind. — Hatha Yoga Pradipika 2.2",
      "Therefore the yogi should restrain the breath; long life results from restraint of the breath. — Hatha Yoga Pradipika 2.3",
      "When all the nadis, which are full of impurities, are purified, then the yogi becomes capable of controlling the prana. — Hatha Yoga Pradipika 2.5",
      "Therefore pranayama should be practiced daily with a sattvic mind, so that the impurities are driven out of the sushumna. — Hatha Yoga Pradipika 2.6",
      "Posture being firmly established, the yogi seated comfortably should perform pranayama. — Hatha Yoga Pradipika 2.7",
      "When the nadis are purified, signs appear in the body — leanness, brightness, and clarity. — Hatha Yoga Pradipika 2.19",
      "He who has gained mastery over the practice should restrain the breath as he wishes. — Hatha Yoga Pradipika 2.16",
      "Just as the lion, the tiger, or the elephant is gradually controlled, so the prana should be gradually controlled. — Hatha Yoga Pradipika 2.15",
      "Otherwise, by sudden practice, the practitioner is destroyed. — Hatha Yoga Pradipika 2.15",
      "By the proper practice of pranayama, all diseases are eradicated. By improper practice, all diseases arise. — Hatha Yoga Pradipika 2.16",
      "The body of one who practices pranayama becomes well-proportioned, fragrant, beautiful, and gracious. — Hatha Yoga Pradipika 2.20",
      "When the prana flows through the sushumna, the mind becomes steady. This steadiness is called the state of unmani. — Hatha Yoga Pradipika 2.42",
      "Mudras should be practiced for the awakening of Kundalini. — Hatha Yoga Pradipika 3.5",
      "As one forces open a door with a key, so the yogi should force the door of liberation with Kundalini. — Hatha Yoga Pradipika 3.105",
      "When Kundalini awakens, all the lotuses and knots are pierced. — Hatha Yoga Pradipika 3.2",
      "The Goddess sleeping at the entrance of Brahmadvara should be constantly aroused. — Hatha Yoga Pradipika 3.5",
      "She who has been awakened by yoga grants liberation. — Hatha Yoga Pradipika 3.111",
      "Maha mudra destroys death and other afflictions. — Hatha Yoga Pradipika 3.16",
      "Wherever the mind goes, the prana goes. Wherever the prana goes, the mind goes. — Hatha Yoga Pradipika 4.24",
      "Thus the mind and the prana are bound together like milk and water. — Hatha Yoga Pradipika 4.24",
      "Where one is, the other is also. If one is destroyed, the other is destroyed. If one acts, the other acts. — Hatha Yoga Pradipika 4.24",
      "When mind and prana are absorbed, all senses cease — that state is called moksha. — Hatha Yoga Pradipika 4.25",
      "When the prana enters the sushumna and the mind is absorbed in the void, then the perfected yogi cuts the bond of action. — Hatha Yoga Pradipika 4.16",
      "Salutations to you, Sushumna, to Kundalini, to the nectar that flows from the moon. — Hatha Yoga Pradipika 4.64",
      "Hear, O Parvati: I shall teach you the science by which death is conquered. — Hatha Yoga Pradipika 3.2",
      "There is no asana like Siddhasana, no kumbhaka like Kevala, no mudra like Khechari, no laya like Nada. — Hatha Yoga Pradipika 1.43",
      "Whatever is here is also there; what is not here is nowhere. — Hatha Yoga Pradipika 4.108",
      "Without Raja Yoga, asanas are useless. Without asanas, Raja Yoga is also useless. So one should practice both. — Hatha Yoga Pradipika 2.76",
      "As salt dissolves in water and becomes one with it, so the union of mind and Self is samadhi. — Hatha Yoga Pradipika 4.5",
      "When the prana is exhausted and the mind is dissolved, then there is the equilibrium called samadhi. — Hatha Yoga Pradipika 4.6",
      "He who knows this is liberated; whoever knows this is free from the cycle of birth and death. — Hatha Yoga Pradipika 4.114",
      "Hatha Yoga is the secret jewel — to be guarded as one guards a precious stone. Reveal it not to those without devotion. — Hatha Yoga Pradipika 1.11"
    ],
    "stoic": [
      "You have power over your mind — not outside events. Realize this, and you will find strength. — Marcus Aurelius, Meditations",
      "The happiness of your life depends upon the quality of your thoughts. — Marcus Aurelius, Meditations",
      "Waste no more time arguing what a good man should be. Be one. — Marcus Aurelius, Meditations 10.16",
      "If it is not right, do not do it; if it is not true, do not say it. — Marcus Aurelius, Meditations 12.17",
      "Confine yourself to the present. — Marcus Aurelius, Meditations 7.29",
      "Do every act of your life as though it were the very last act of your life. — Marcus Aurelius, Meditations 2.5",
      "How much trouble he avoids who does not look to see what his neighbor says or does. — Marcus Aurelius, Meditations 4.18",
      "The best revenge is to be unlike him who performed the injury. — Marcus Aurelius, Meditations 6.6",
      "Begin the morning by saying to yourself: I shall meet with the busybody, the ungrateful, the arrogant — none of them can hurt me. — Marcus Aurelius, Meditations 2.1",
      "When you arise in the morning, think of what a precious privilege it is to be alive — to breathe, to think, to enjoy, to love. — Marcus Aurelius, Meditations",
      "It is not death that a man should fear, but he should fear never beginning to live. — Marcus Aurelius, Meditations",
      "Look well into thyself; there is a source of strength which will always spring up if thou wilt always look. — Marcus Aurelius, Meditations 7.59",
      "The impediment to action advances action. What stands in the way becomes the way. — Marcus Aurelius, Meditations 5.20",
      "Very little is needed to make a happy life; it is all within yourself, in your way of thinking. — Marcus Aurelius, Meditations",
      "It is in your power to withdraw yourself whenever you desire. — Marcus Aurelius, Meditations 4.3",
      "Some things are in our control, and others are not. — Epictetus, Enchiridion 1",
      "It is not what happens to you, but how you react to it that matters. — Epictetus",
      "No man is free who is not master of himself. — Epictetus",
      "First say to yourself what you would be; and then do what you have to do. — Epictetus, Discourses 3.23",
      "He who laughs at himself never runs out of things to laugh at. — Epictetus",
      "Wealth consists not in having great possessions, but in having few wants. — Epictetus",
      "Don't explain your philosophy. Embody it. — Epictetus",
      "Make the best use of what is in your power, and take the rest as it happens. — Epictetus, Discourses",
      "If you wish to improve, be content to appear clueless or stupid in extraneous matters. — Epictetus, Enchiridion 13",
      "Circumstances don't make the man; they only reveal him to himself. — Epictetus",
      "Other people's views and troubles can be contagious. Don't sabotage yourself by unwittingly adopting negative thoughts. — Epictetus",
      "Difficulties show a person's character. So when a hard task befalls you, remember: God is matching you with a younger sparring partner. — Epictetus, Discourses 1.24",
      "We have two ears and one mouth so that we can listen twice as much as we speak. — Epictetus",
      "It is impossible for a man to learn what he thinks he already knows. — Epictetus, Discourses 2.17",
      "We are more often frightened than hurt; and we suffer more in imagination than in reality. — Seneca, Letters",
      "Luck is what happens when preparation meets opportunity. — Seneca",
      "It is not the man who has too little, but the man who craves more, that is poor. — Seneca, Letters 2",
      "He who is brave is free. — Seneca",
      "While we wait for life, life passes. — Seneca, Letters 1",
      "It is not that we have a short time to live, but that we waste a lot of it. — Seneca, On the Shortness of Life",
      "Begin at once to live, and count each separate day as a separate life. — Seneca, Letters 101",
      "Every new beginning comes from some other beginning's end. — Seneca",
      "Sometimes even to live is an act of courage. — Seneca, Letters 78",
      "No man was ever wise by chance. — Seneca, Letters 76",
      "Difficulties strengthen the mind, as labor does the body. — Seneca"
    ]
  },
  "ru": {
    "yoga_sutra": [
      "Атха йогануш́асанам — итак, начинается изложение йоги. — Йога-сутра 1.1",
      "Йога есть прекращение колебаний ума. — Йога-сутра 1.2",
      "Тогда видящий пребывает в своей собственной природе. — Йога-сутра 1.3",
      "В иное время видящий принимает форму колебаний ума. — Йога-сутра 1.4",
      "Практика и непривязанность — средства для остановки движений сознания. — Йога-сутра 1.12",
      "Практика есть постоянное усилие пребывать в этом состоянии. — Йога-сутра 1.13",
      "Практика становится прочной, когда совершается долго, без перерывов и с искренней преданностью. — Йога-сутра 1.14",
      "Майтри, каруна, мудита, упекшанам — дружелюбие, сострадание, радость, беспристрастность. — Йога-сутра 1.33",
      "Когда возникают негативные мысли, следует культивировать противоположные. — Йога-сутра 2.33",
      "Страдания, которые ещё не наступили, можно и должно избегать. — Йога-сутра 2.16",
      "Невежество — принятие непостоянного за постоянное, нечистого за чистое, страдания за счастье, не-Я за Я. — Йога-сутра 2.5",
      "Асана — устойчивая и удобная. — Йога-сутра 2.46",
      "Освобождением от усилия и медитацией на бесконечном асана осваивается. — Йога-сутра 2.47",
      "Тогда практикующего более не беспокоят пары противоположностей. — Йога-сутра 2.48",
      "Пранаяма — сознательное прекращение движения вдоха и выдоха. — Йога-сутра 2.49",
      "Тогда покров внутреннего света рассеивается. — Йога-сутра 2.52",
      "И ум становится способным к концентрации. — Йога-сутра 2.53",
      "Пратьяхара — отрешение чувств от их объектов. — Йога-сутра 2.54",
      "Из этого возникает высшее владение чувствами. — Йога-сутра 2.55",
      "Дхарана — удержание сознания в одной точке. — Йога-сутра 3.1",
      "Дхьяна — непрерывное течение сознания к этой точке. — Йога-сутра 3.2",
      "Самадхи — когда сияет один лишь объект, как будто собственная форма исчезла. — Йога-сутра 3.3",
      "Эти три вместе называются самьяма. — Йога-сутра 3.4",
      "Хеям духкхам анагатам — страдания, которых ещё нет, должны быть устранены. — Йога-сутра 2.16",
      "Поза, дыхание, чувства, освоенные, готовят ум к тому, чего нельзя достичь силой. — Йога-сутра 2.46–2.55",
      "Тапас, свадхьяя, ишвара-пранидхана — дисциплина, самопознание, преданность — это крийя-йога. — Йога-сутра 2.1",
      "Через крийя-йогу ослабевают клеши и достигается самадхи. — Йога-сутра 2.2",
      "Пять клеш: невежество, эго, привязанность, отвращение, страх смерти. — Йога-сутра 2.3",
      "Невежество — поле для остальных. — Йога-сутра 2.4",
      "Когда возникает истинное знание, причина страдания исчезает. — Йога-сутра 2.25",
      "Ямы: ненасилие, правдивость, неворовство, воздержание, нестяжание. — Йога-сутра 2.30",
      "Эти ямы — великий обет, не обусловленный местом, временем или обстоятельствами. — Йога-сутра 2.31",
      "Ниямы: чистота, удовлетворённость, дисциплина, самопознание, преданность. — Йога-сутра 2.32",
      "Когда утверждено ненасилие, в присутствии практикующего прекращается враждебность. — Йога-сутра 2.35",
      "Когда утверждена правдивость, слова становятся плодоносными. — Йога-сутра 2.36",
      "Из удовлетворённости — высшее счастье. — Йога-сутра 2.42",
      "Из самопознания — соединение с избранным идеалом. — Йога-сутра 2.44",
      "Из преданности Господу — достижение самадхи. — Йога-сутра 2.45",
      "Истинное знание, ошибка, воображение, сон и память — пять колебаний. — Йога-сутра 1.6",
      "Их прекращение достигается практикой и бесстрастием. — Йога-сутра 1.12"
    ],
    "bhagavad_gita": [
      "У тебя есть право на действие, но никогда — на его плоды. Пусть плоды действия не будут твоим мотивом, но и бездействию не привязывайся. — Бхагавад-гита 2.47",
      "Йога есть искусство в действии. — Бхагавад-гита 2.50",
      "Йога есть невозмутимость ума. — Бхагавад-гита 2.48",
      "Когда медитация достигнута, ум неподвижен — как пламя лампы в безветренном месте. — Бхагавад-гита 6.19",
      "Для того, кто овладел умом, ум — лучший друг; для того, кто не овладел — ум остаётся злейшим врагом. — Бхагавад-гита 6.6",
      "Душа не рождается и не умирает. — Бхагавад-гита 2.20",
      "Оружие не рассекает её, огонь не сжигает её, вода не увлажняет её, ветер не иссушает её. — Бхагавад-гита 2.23",
      "Кто видит бездействие в действии и действие в бездействии — тот мудр среди людей. — Бхагавад-гита 4.18",
      "Тот, кто свободен от привязанностей, чей ум утвердился в знании — его действия растворяются. — Бхагавад-гита 4.23",
      "Лучше своя дхарма, исполненная несовершенно, чем чужая дхарма, исполненная превосходно. — Бхагавад-гита 3.35",
      "Исполняй свой долг, оставив привязанность к успеху и неудаче. — Бхагавад-гита 2.48",
      "Тот, кто обуздал чувства умом и направил их на путь действия без привязанности — превосходит. — Бхагавад-гита 3.7",
      "От гнева — заблуждение; от заблуждения — потеря памяти; от потери памяти — разрушение разума; от этого — гибель. — Бхагавад-гита 2.63",
      "Когда чувства движутся среди объектов без желания и отвращения, под властью самого себя — приходит покой. — Бхагавад-гита 2.64",
      "В покое все скорби заканчиваются; разум того, кто спокоен, скоро утверждается. — Бхагавад-гита 2.65",
      "Тот, чей ум невозмутим в скорби, свободен от желаний в радости, свободен от страсти, страха и гнева — мудрец устойчивого знания. — Бхагавад-гита 2.56",
      "Как сильный ветер уносит лодку по водам, так одно блуждающее чувство уносит мудрость того, кто не владеет собой. — Бхагавад-гита 2.67",
      "Что для всех существ ночь — то для дисциплинированного время бодрствования; что для всех бодрствование — то для мудреца ночь. — Бхагавад-гита 2.69",
      "Покой обретает тот, в кого все желания входят, как воды входят в полный океан, оставаясь неподвижным. — Бхагавад-гита 2.70",
      "Йога не для того, кто ест слишком много или слишком мало; не для того, кто спит слишком много или совсем не спит. — Бхагавад-гита 6.16",
      "Йога становится разрушителем боли для того, кто умерен в еде и отдыхе, уравновешен в действии, во сне и бодрствовании. — Бхагавад-гита 6.17",
      "Подними себя сам — не позволяй себе пасть. Ибо лишь сам себе ты друг, и лишь сам себе ты враг. — Бхагавад-гита 6.5",
      "Куда бы ни блуждал беспокойный, неустойчивый ум — возвращай его обратно под власть Атмана. — Бхагавад-гита 6.26",
      "Тот, кто видит Себя во всех существах и все существа в Себе — тот никогда не отворачивается от Него. — Бхагавад-гита 6.30",
      "Среди тысяч людей едва ли один стремится к совершенству; среди стремящихся едва ли один знает Меня по истине. — Бхагавад-гита 7.3",
      "Что бы ты ни делал, что бы ни ел, что бы ни приносил в жертву, что бы ни давал, что бы ни практиковал — делай это как подношение. — Бхагавад-гита 9.27",
      "Я — время, разрушитель миров. — Бхагавад-гита 11.32",
      "Тот, кто не питает злобы ни к одному существу, кто дружелюбен и сострадателен — тот дорог Мне. — Бхагавад-гита 12.13",
      "Удовлетворённый тем, что приходит, выше двойственности, свободный от зависти, уравновешенный в успехе и неудаче — он дорог Мне. — Бхагавад-гита 12.18",
      "Тот, кто переносит холод и зной, радость и скорбь с равновесием — достоин бессмертия. — Бхагавад-гита 2.15",
      "У нереального нет бытия; реальное никогда не перестаёт быть. — Бхагавад-гита 2.16",
      "Как человек снимает старую одежду и надевает новую, так душа принимает новые тела, оставляя старые. — Бхагавад-гита 2.22",
      "Вера делает человека тем, какова его вера. — Бхагавад-гита 17.3",
      "Тот, чьи действия свободны от связи с желанием, чья карма сожжена в огне знания — мудрого называют учёным. — Бхагавад-гита 4.19",
      "Оставь все обязанности и предайся Мне; Я освобожу тебя от всех грехов. Не скорби. — Бхагавад-гита 18.66",
      "Нет в трёх мирах ничего, что Мне нужно делать или достигать — но Я действую. — Бхагавад-гита 3.22",
      "Что бы ни делал великий человек, тому следуют другие. Стандарт, который он ставит, мир преследует. — Бхагавад-гита 3.21",
      "Лучше своя дхарма, пусть несовершенная, чем чужая, исполненная превосходно. — Бхагавад-гита 18.47",
      "Истинно отрешённый — тот, кто не ненавидит и не желает. — Бхагавад-гита 5.3",
      "Йог, гармоничный в радости и скорби, в чести и бесчестии — он перешёл за пределы. — Бхагавад-гита 6.7"
    ],
    "hatha_yoga_pradipika": [
      "Поклон Адинатхе, который преподал Хатха-видью как ступень к высотам Раджа-йоги. — Хатха-йога-прадипика 1.1",
      "Хатха-йога — для тех, кто беспокоен в Раджа-йоге, прибежище для тех, кто опалён жаром мира. — Хатха-йога-прадипика 1.10",
      "Йога разрушается шестью причинами: переедание, излишнее усилие, болтливость, аскетизм, общение с людьми, неустойчивость. — Хатха-йога-прадипика 1.15",
      "Йога удаётся шестью причинами: воодушевление, упорство, различение, вера, мужество, избегание общества обычных людей. — Хатха-йога-прадипика 1.16",
      "Асана — первая ступень Хатха-йоги — описывается первой. Она даёт устойчивость, здоровье и лёгкость тела. — Хатха-йога-прадипика 1.17",
      "Через её практику тело становится сильным, ум — спокойным, а ученик — свободным от болезней. — Хатха-йога-прадипика 1.18",
      "Падмасана разрушает все болезни практикующего. — Хатха-йога-прадипика 1.47",
      "Пища сладкая, маслянистая, молочная, питающая дхату, приятная и подходящая — такую пищу должен есть йог. — Хатха-йога-прадипика 1.63",
      "Когда дыхание блуждает, ум неустойчив. Когда дыхание спокойно, спокоен и ум. — Хатха-йога-прадипика 2.2",
      "Поэтому йог должен сдерживать дыхание; долгая жизнь — результат сдерживания дыхания. — Хатха-йога-прадипика 2.3",
      "Когда все нади, полные нечистот, очищены, тогда йог становится способен управлять праной. — Хатха-йога-прадипика 2.5",
      "Поэтому пранаяму следует практиковать ежедневно с саттвическим умом, чтобы нечистоты были изгнаны из сушумны. — Хатха-йога-прадипика 2.6",
      "Когда поза прочно установлена, йог, удобно сидящий, должен выполнять пранаяму. — Хатха-йога-прадипика 2.7",
      "Когда нади очищены, в теле появляются признаки — стройность, ясность и сияние. — Хатха-йога-прадипика 2.19",
      "Тот, кто овладел практикой, может задерживать дыхание сколь угодно долго. — Хатха-йога-прадипика 2.16",
      "Как лев, тигр или слон постепенно подчиняются, так и прана должна подчиняться постепенно. — Хатха-йога-прадипика 2.15",
      "Иначе, при внезапной практике, практикующий разрушается. — Хатха-йога-прадипика 2.15",
      "Через правильную практику пранаямы все болезни искореняются. Через неправильную — все болезни возникают. — Хатха-йога-прадипика 2.16",
      "Тело того, кто практикует пранаяму, становится стройным, ароматным, прекрасным и милостивым. — Хатха-йога-прадипика 2.20",
      "Когда прана течёт через сушумну, ум становится устойчивым. Эта устойчивость — состояние унмани. — Хатха-йога-прадипика 2.42",
      "Мудры следует практиковать для пробуждения Кундалини. — Хатха-йога-прадипика 3.5",
      "Как открывают дверь ключом, так йог должен открыть дверь освобождения Кундалини. — Хатха-йога-прадипика 3.105",
      "Когда Кундалини пробуждается, все лотосы и узлы пронзаются. — Хатха-йога-прадипика 3.2",
      "Богиня, спящая у входа Брахмадвары, должна постоянно пробуждаться. — Хатха-йога-прадипика 3.5",
      "Та, что пробуждена йогой, дарует освобождение. — Хатха-йога-прадипика 3.111",
      "Маха-мудра разрушает смерть и другие страдания. — Хатха-йога-прадипика 3.16",
      "Куда движется ум, туда движется прана. Куда движется прана, туда движется ум. — Хатха-йога-прадипика 4.24",
      "Так ум и прана связаны вместе, как молоко и вода. — Хатха-йога-прадипика 4.24",
      "Где одно — там и другое. Если разрушено одно — разрушено и другое. Если действует одно — действует и другое. — Хатха-йога-прадипика 4.24",
      "Когда ум и прана поглощены, все чувства останавливаются — это состояние называется мокша. — Хатха-йога-прадипика 4.25",
      "Когда прана входит в сушумну и ум поглощается в пустоте, тогда совершенный йог рассекает оковы кармы. — Хатха-йога-прадипика 4.16",
      "Поклон тебе, Сушумна, Кундалини, нектар, текущий с луны. — Хатха-йога-прадипика 4.64",
      "Слушай, о Парвати: я преподам тебе науку, которой побеждается смерть. — Хатха-йога-прадипика 3.2",
      "Нет асаны как Сиддхасана, нет кумбхаки как Кевала, нет мудры как Кхечари, нет лайи как Нада. — Хатха-йога-прадипика 1.43",
      "Что есть здесь — есть и там; чего нет здесь — нет нигде. — Хатха-йога-прадипика 4.108",
      "Без Раджа-йоги асаны бесполезны. Без асан и Раджа-йога бесполезна. Поэтому надо практиковать обе. — Хатха-йога-прадипика 2.76",
      "Как соль растворяется в воде и становится единой с ней, так союз ума и Атмана есть самадхи. — Хатха-йога-прадипика 4.5",
      "Когда прана истощена и ум растворён, наступает равновесие, называемое самадхи. — Хатха-йога-прадипика 4.6",
      "Кто знает это — тот освобождён; кто знает это — свободен от круга рождения и смерти. — Хатха-йога-прадипика 4.114",
      "Хатха-йога — тайная драгоценность; храни её как драгоценный камень. Не открывай тем, в ком нет преданности. — Хатха-йога-прадипика 1.11"
    ],
    "stoic": [
      "Ты властен над своим умом — а не над внешними событиями. Осознай это, и обретёшь силу. — Марк Аврелий, К самому себе",
      "Счастье твоей жизни зависит от качества твоих мыслей. — Марк Аврелий, К самому себе",
      "Не трать больше времени на споры о том, каким должен быть хороший человек. Будь им. — Марк Аврелий, К самому себе 10.16",
      "Если это не правильно — не делай этого; если это не истинно — не говори этого. — Марк Аврелий, К самому себе 12.17",
      "Ограничь себя настоящим. — Марк Аврелий, К самому себе 7.29",
      "Делай каждый поступок жизни так, будто он последний. — Марк Аврелий, К самому себе 2.5",
      "Сколько хлопот избегает тот, кто не смотрит, что говорит или делает его сосед. — Марк Аврелий, К самому себе 4.18",
      "Лучшая месть — не быть похожим на того, кто причинил вред. — Марк Аврелий, К самому себе 6.6",
      "Начни утро словами: я встречу занятого, неблагодарного, надменного — никто из них не сможет повредить мне. — Марк Аврелий, К самому себе 2.1",
      "Когда просыпаешься утром, думай о драгоценной привилегии быть живым — дышать, мыслить, наслаждаться, любить. — Марк Аврелий, К самому себе",
      "Не смерти должен бояться человек, а того, что никогда не начнёт жить. — Марк Аврелий, К самому себе",
      "Загляни внутрь себя; там есть источник силы, который всегда забьёт, если будешь смотреть. — Марк Аврелий, К самому себе 7.59",
      "Препятствие действию продвигает действие. То, что стоит на пути, становится путём. — Марк Аврелий, К самому себе 5.20",
      "Очень мало нужно для счастливой жизни; всё внутри тебя, в твоём способе мышления. — Марк Аврелий, К самому себе",
      "В твоей власти удалиться в себя когда пожелаешь. — Марк Аврелий, К самому себе 4.3",
      "Одно в нашей власти, другое — нет. — Эпиктет, Энхиридион 1",
      "Не то, что с тобой случается, а как ты на это реагируешь — вот что важно. — Эпиктет",
      "Никто не свободен, кто не владеет собой. — Эпиктет",
      "Сначала скажи себе, кем хочешь быть; затем делай то, что должен. — Эпиктет, Беседы 3.23",
      "Тот, кто смеётся над собой, никогда не останется без повода для смеха. — Эпиктет",
      "Богатство состоит не в обладании многим, а в малом числе желаний. — Эпиктет",
      "Не объясняй свою философию. Воплощай её. — Эпиктет",
      "Используй наилучшим образом то, что в твоей власти, и принимай остальное как есть. — Эпиктет, Беседы",
      "Если хочешь совершенствоваться — будь готов казаться глупым в посторонних делах. — Эпиктет, Энхиридион 13",
      "Обстоятельства не делают человека; они только открывают его самому себе. — Эпиктет",
      "Чужие взгляды и тревоги заразны. Не вреди себе, бессознательно перенимая чужие негативные мысли. — Эпиктет",
      "Трудности проявляют характер. Когда выпадает тяжёлая задача — помни: бог сводит тебя с молодым спарринг-партнёром. — Эпиктет, Беседы 1.24",
      "У нас два уха и один рот, чтобы слушать вдвое больше, чем говорить. — Эпиктет",
      "Невозможно научиться тому, что считаешь, будто уже знаешь. — Эпиктет, Беседы 2.17",
      "Мы чаще боимся, чем страдаем; и страдаем больше в воображении, чем в реальности. — Сенека, Письма",
      "Удача — это то, что случается, когда подготовка встречает возможность. — Сенека",
      "Беден не тот, у кого мало, а тот, кто желает большего. — Сенека, Письма 2",
      "Кто храбр — тот свободен. — Сенека",
      "Пока мы откладываем жизнь — она проходит. — Сенека, Письма 1",
      "Не то что у нас мало времени — мы тратим его впустую. — Сенека, О краткости жизни",
      "Начинай жить сейчас же; считай каждый отдельный день отдельной жизнью. — Сенека, Письма 101",
      "Каждое новое начало рождается из конца другого начала. — Сенека",
      "Иногда даже жить — акт мужества. — Сенека, Письма 78",
      "Никто никогда не стал мудрым случайно. — Сенека, Письма 76",
      "Трудности укрепляют ум, как труд укрепляет тело. — Сенека"
    ]
  },
  "zh": {
    "yoga_sutra": [
      "Atha Yoganushasanam — 此时，瑜伽之教导开始。— 瑜伽经 1.1",
      "瑜伽是心意波动的止息。— 瑜伽经 1.2",
      "此时，见者安住于其本性。— 瑜伽经 1.3",
      "其他时候，见者认同于波动。— 瑜伽经 1.4",
      "练习与不执着，是平息心意活动的方法。— 瑜伽经 1.12",
      "练习是为了保持那种状态而做的持续努力。— 瑜伽经 1.13",
      "长久不断、虔诚地练习，根基方能稳固。— 瑜伽经 1.14",
      "慈、悲、喜、舍——四无量心。— 瑜伽经 1.33",
      "当负面思维生起时，应培养相反的思维。— 瑜伽经 2.33",
      "未来之苦，可以避免。— 瑜伽经 2.16",
      "无明，是把无常当作常，把不净当作净，把苦当作乐，把非我当作我。— 瑜伽经 2.5",
      "体式应当稳定而舒适。— 瑜伽经 2.46",
      "通过放松努力、冥想无限，体式得以掌握。— 瑜伽经 2.47",
      "如此，练习者不再为对立的两极所扰。— 瑜伽经 2.48",
      "调息，是有意识地止息呼吸的运动。— 瑜伽经 2.49",
      "如此，遮蔽内在之光的帷幕消散。— 瑜伽经 2.52",
      "于是，心适于专注。— 瑜伽经 2.53",
      "制感，是感官从其对象中收摄。— 瑜伽经 2.54",
      "由此，对感官获得最高的掌控。— 瑜伽经 2.55",
      "专注，是将意识系于一处。— 瑜伽经 3.1",
      "禅那，是意识不间断地流向那一处。— 瑜伽经 3.2",
      "三摩地，是唯有对象闪耀，仿佛自身已不存在。— 瑜伽经 3.3",
      "此三者合称为三耶摩。— 瑜伽经 3.4",
      "Heyam dukham anagatam — 未来未生之苦，可以止息。— 瑜伽经 2.16",
      "调身、调息、调感，皆已掌握，方能安心于不可强求之境。— 瑜伽经 2.46–2.55",
      "苦行、自学、奉献于神——此即克利亚瑜伽。— 瑜伽经 2.1",
      "依克利亚瑜伽，烦恼削弱，三摩地得养。— 瑜伽经 2.2",
      "五烦恼：无明、我执、贪爱、嗔恨、惧死。— 瑜伽经 2.3",
      "无明，是其余烦恼的温床。— 瑜伽经 2.4",
      "正智生起时，苦因即灭。— 瑜伽经 2.25",
      "禁戒：不害、真实、不偷、节欲、不执。— 瑜伽经 2.30",
      "此五禁戒为大誓，无论何时何地何境，皆当奉行。— 瑜伽经 2.31",
      "劝戒：净洁、知足、苦行、自学、奉献。— 瑜伽经 2.32",
      "不害已立，敌意于练习者前自息。— 瑜伽经 2.35",
      "真实已立，所言皆有果。— 瑜伽经 2.36",
      "由知足，得无上之乐。— 瑜伽经 2.42",
      "由自学，与所选之理想相通。— 瑜伽经 2.44",
      "由奉献于神，得三摩地。— 瑜伽经 2.45",
      "正知、错觉、妄想、睡眠、记忆——此为五种波动。— 瑜伽经 1.6",
      "通过练习与不执，平息此五者。— 瑜伽经 1.12"
    ],
    "bhagavad_gita": [
      "你只有行动的权利，从无对结果的权利。莫以结果为动机，亦莫执着于不行动。— 薄伽梵歌 2.47",
      "瑜伽是行动中的技艺。— 薄伽梵歌 2.50",
      "瑜伽是心的平等。— 薄伽梵歌 2.48",
      "禅定既至，心如无风之处的灯焰，不动摇。— 薄伽梵歌 6.19",
      "已征服自心者，心是最好的朋友；未征服者，心是最大的敌人。— 薄伽梵歌 6.6",
      "灵魂不生不灭。— 薄伽梵歌 2.20",
      "兵器不能斫之，烈火不能焚之，水不能湿之，风不能干之。— 薄伽梵歌 2.23",
      "于行中见无行，于无行中见行——此人于人中为智者。— 薄伽梵歌 4.18",
      "无所执着、自由、心立于智慧者——其作为消融。— 薄伽梵歌 4.23",
      "宁守自己的法而行不善，胜过遵他人之法而行善。— 薄伽梵歌 3.35",
      "履行你的职责，平等无别，舍弃对成败的执着。— 薄伽梵歌 2.48",
      "以心制感，无所执着地行于行动之路者——卓尔不群。— 薄伽梵歌 3.7",
      "由怒生迷；由迷失忆；由失忆乱智；由乱智，毁灭。— 薄伽梵歌 2.63",
      "感官在境界中行动，无贪无嗔，自心调御者——得寂静。— 薄伽梵歌 2.64",
      "于寂静中，一切忧愁灭尽；寂静者之智速立。— 薄伽梵歌 2.65",
      "心于忧不动，于乐不贪，离激情、恐惧与愤怒——是稳定之智者。— 薄伽梵歌 2.56",
      "如狂风卷舟于水，一念游荡之感官，可夺去未自御者之智。— 薄伽梵歌 2.67",
      "众生之夜，乃自律者之昼；众生之昼，乃见者之夜。— 薄伽梵歌 2.69",
      "诸欲入于此人，如水入满海而海不动——彼得寂静。— 薄伽梵歌 2.70",
      "瑜伽不属于多食者，亦不属于不食者；不属于多睡者，亦不属于不眠者。— 薄伽梵歌 6.16",
      "饮食有节、行止有度、起卧有时者——瑜伽即苦之灭者。— 薄伽梵歌 6.17",
      "以己自举，勿令自堕。自己即是自己的友，自己即是自己的敌。— 薄伽梵歌 6.5",
      "无论不安之心驰向何处——皆当收回，置于阿特曼之下。— 薄伽梵歌 6.26",
      "于一切众生中见自己，于自己中见一切众生者——彼永不背离之。— 薄伽梵歌 6.30",
      "万千人中，求圆满者寥寥；求者中，真知我者更稀。— 薄伽梵歌 7.3",
      "无论你做什么、吃什么、献什么、施什么、修什么——皆作为奉献而行。— 薄伽梵歌 9.27",
      "我是时间，世界的毁灭者。— 薄伽梵歌 11.32",
      "无害于一切众生，友善而慈悲者——是为我所亲。— 薄伽梵歌 12.13",
      "随遇而安，超越对立，无嫉妒，平等于成败者——是为我所亲。— 薄伽梵歌 12.18",
      "能以平等心忍受寒热、苦乐者——堪受不朽。— 薄伽梵歌 2.15",
      "非真者无存在；真者从不停息。— 薄伽梵歌 2.16",
      "如人脱旧衣而着新衣，灵魂舍旧身而受新身。— 薄伽梵歌 2.22",
      "信使人成为其信之所是。— 薄伽梵歌 17.3",
      "其行无欲所缚，其业焚于智之火者——智者称之为有学。— 薄伽梵歌 4.19",
      "舍一切义务，归依于我；我必使你脱一切罪。莫忧。— 薄伽梵歌 18.66",
      "三界之中，我无所须为，无所须得——然我恒行。— 薄伽梵歌 3.22",
      "凡大人物所为，他人皆从之。彼立之标，世人皆追。— 薄伽梵歌 3.21",
      "宁守自己之法不全，胜过完美履行他人之法。— 薄伽梵歌 18.47",
      "真正的弃舍者，是无憎亦无欲者。— 薄伽梵歌 5.3",
      "瑜伽士于苦乐、荣辱中皆和——彼已超越。— 薄伽梵歌 6.7"
    ],
    "hatha_yoga_pradipika": [
      "礼敬阿迪那特，他将哈他之法授予作通向王瑜伽之阶梯。— 哈他瑜伽之光 1.1",
      "哈他瑜伽，为不安于王瑜伽者而设；亦为受世火所灼者之庇护。— 哈他瑜伽之光 1.10",
      "六事毁瑜伽：饮食过度、用力过度、多语、苦行、众处、不定。— 哈他瑜伽之光 1.15",
      "六事成瑜伽：热忱、坚毅、明辨、信心、勇气、远离俗众。— 哈他瑜伽之光 1.16",
      "体式为哈他瑜伽之首，先述之。它给予稳定、健康与轻盈。— 哈他瑜伽之光 1.17",
      "藉其修习，身强、心定、修者离病。— 哈他瑜伽之光 1.18",
      "莲花式破修者一切病。— 哈他瑜伽之光 1.47",
      "甘、油、乳、滋养七界、悦意而合宜之食——瑜伽士当食之。— 哈他瑜伽之光 1.63",
      "息散则心散；息定则心定。— 哈他瑜伽之光 2.2",
      "故瑜伽士当制其息；制息则寿长。— 哈他瑜伽之光 2.3",
      "诸脉满垢者一旦清净，瑜伽士方能制气。— 哈他瑜伽之光 2.5",
      "故应每日以纯净之心修调息，使垢出于中脉。— 哈他瑜伽之光 2.6",
      "体式既稳，瑜伽士安坐，当行调息。— 哈他瑜伽之光 2.7",
      "诸脉清净时，身现清征——清瘦、明亮、洁净。— 哈他瑜伽之光 2.19",
      "已得修习自在者，可随意持息。— 哈他瑜伽之光 2.16",
      "如狮、虎、象渐次驯服，气亦当渐次驯服。— 哈他瑜伽之光 2.15",
      "否则，骤行之，修者必毁。— 哈他瑜伽之光 2.15",
      "调息正修，万病可除；妄修，则万病丛生。— 哈他瑜伽之光 2.16",
      "调息修者，身匀称、芳馨、美丽、温雅。— 哈他瑜伽之光 2.20",
      "气入中脉时，心即定。此定名为「无心」之境。— 哈他瑜伽之光 2.42",
      "为唤醒昆达里尼，应修身印。— 哈他瑜伽之光 3.5",
      "如以钥开门，瑜伽士当以昆达里尼开解脱之门。— 哈他瑜伽之光 3.105",
      "昆达里尼觉醒时，一切莲花与结皆穿。— 哈他瑜伽之光 3.2",
      "卧于梵门之女神，应不断唤醒。— 哈他瑜伽之光 3.5",
      "她由瑜伽所唤醒者，赐予解脱。— 哈他瑜伽之光 3.111",
      "大身印破死与诸苦。— 哈他瑜伽之光 3.16",
      "心所至处，气至焉。气所至处，心至焉。— 哈他瑜伽之光 4.24",
      "故心与气如乳与水，相系而行。— 哈他瑜伽之光 4.24",
      "一者所在，他者亦在。一者灭，他者亦灭。一者动，他者亦动。— 哈他瑜伽之光 4.24",
      "心与气俱寂，诸感息止——此境名解脱。— 哈他瑜伽之光 4.25",
      "气入中脉、心入空寂，圆满瑜伽士斩业之系。— 哈他瑜伽之光 4.16",
      "礼敬汝，中脉、昆达里尼、自月而流之甘露。— 哈他瑜伽之光 4.64",
      "听吧，帕尔瓦蒂：我授汝胜死之法。— 哈他瑜伽之光 3.2",
      "无如悉达式之体式，无如克瓦拉之止息，无如逆舌之身印，无如内音之消融。— 哈他瑜伽之光 1.43",
      "此处所有，彼处亦有；此处所无，彼处亦无。— 哈他瑜伽之光 4.108",
      "无王瑜伽，体式无用；无体式，王瑜伽亦无用。故应同修。— 哈他瑜伽之光 2.76",
      "如盐溶于水而成一体，心与自我之合一即三摩地。— 哈他瑜伽之光 4.5",
      "气竭、心融，乃名三摩地之均衡。— 哈他瑜伽之光 4.6",
      "知此者解脱；知此者脱生死之轮。— 哈他瑜伽之光 4.114",
      "哈他瑜伽是秘宝——当如珍宝守护。莫示无信之人。— 哈他瑜伽之光 1.11"
    ],
    "stoic": [
      "你能掌控的是自己的心，而非外境。明此即得力。— 马可·奥勒留《沉思录》",
      "生命之乐，系于思维之质。— 马可·奥勒留《沉思录》",
      "莫再争论好人当如何，当一个就是。— 马可·奥勒留《沉思录》10.16",
      "非正勿行；非真勿言。— 马可·奥勒留《沉思录》12.17",
      "把自己限于当下。— 马可·奥勒留《沉思录》7.29",
      "做生命中的每件事，皆如最后一件。— 马可·奥勒留《沉思录》2.5",
      "不看邻人之言行者，免去多少麻烦。— 马可·奥勒留《沉思录》4.18",
      "最好的报复，是不与作恶者相同。— 马可·奥勒留《沉思录》6.6",
      "晨起当言：我今日将遇忙人、负心人、倨傲人——彼皆不能伤我。— 马可·奥勒留《沉思录》2.1",
      "晨起，思活着乃何等珍贵——能呼吸、能思、能享、能爱。— 马可·奥勒留《沉思录》",
      "人当畏者，非死，乃从未真正活过。— 马可·奥勒留《沉思录》",
      "向内观照；其中有一源头之力，凡求者必得。— 马可·奥勒留《沉思录》7.59",
      "障碍即是道路。横在路上者，化为路本身。— 马可·奥勒留《沉思录》5.20",
      "幸福一生所需甚少；皆在你心中，在你思之方式。— 马可·奥勒留《沉思录》",
      "你随时可退入自己。— 马可·奥勒留《沉思录》4.3",
      "有些事在我们掌控之中，有些不在。— 爱比克泰德《手册》1",
      "不是发生了什么，而是你如何回应——这才是关键。— 爱比克泰德",
      "不能自主者，不得自由。— 爱比克泰德",
      "先告诉自己想成为谁；然后做你必须做的。— 爱比克泰德《语录》3.23",
      "能笑己者，永不缺笑料。— 爱比克泰德",
      "富者，不在多有，而在少欲。— 爱比克泰德",
      "莫释你的哲学。当体现之。— 爱比克泰德",
      "尽其在我者，余者随之。— 爱比克泰德《语录》",
      "若欲精进，须能在闲事上看似愚笨而不计较。— 爱比克泰德《手册》13",
      "境遇不造人，只显其人于己。— 爱比克泰德",
      "他人之见与忧虑可染人。莫不察而采其负思以害己。— 爱比克泰德",
      "难事见品格。重任至时，记得：神为你配了年轻的对手。— 爱比克泰德《语录》1.24",
      "二耳一口——听当倍于言。— 爱比克泰德",
      "自以为已知者，无从学之。— 爱比克泰德《语录》2.17",
      "我们所惧多于所伤；想象中所受之苦多于现实。— 塞涅卡《道德书简》",
      "运气，是准备遇上机会。— 塞涅卡",
      "贫者，非物寡，乃贪多者。— 塞涅卡《道德书简》2",
      "勇者即自由。— 塞涅卡",
      "我们等候人生时，人生已逝。— 塞涅卡《道德书简》1",
      "非我们寿短，乃我们多虚度。— 塞涅卡《论生命之短暂》",
      "立时开始活；视每日为一独立之生。— 塞涅卡《道德书简》101",
      "每个新的开端，都源于另一个开端的终结。— 塞涅卡",
      "有时，活着本身即是勇气之举。— 塞涅卡《道德书简》78",
      "无人偶然成智者。— 塞涅卡《道德书简》76",
      "困难强心，犹劳作强身。— 塞涅卡"
    ]
  }
};
