# Content for the two new tabs. Stories come from the checked research (verified.json, 10 Oct 2026).
# Jokes target Boonchu only. No ages stated. Facts reused from his own page: twenty years, up at four, stiff hamstrings, glasses, socks.

A_GROUPS = [
 ('Asanas named after long-life stories', [
  dict(id='kurma', t='The tortoise who held a mountain', a='Kurmasana, Supta Kurmasana · Primary',
   s="The story goes that the gods and the asuras churned the ocean for amrita, the nectar of long life. A mountain was the churning stick, and a tortoise held it on his back. In the Bhagavata Purana the tortoise is Vishnu, and the turning mountain felt like a nice back scratch.",
   src=("Mahabharata, Adi Parva 18 (Ganguli); Bhagavata Purana 8.7.10", "https://vedabase.io/en/library/sb/8/7/10/"),
   j=[(28, "I asked my back about Supta Kurmasana. It said the tortoise held a whole mountain and called it a back scratch. Then it asked me to stop calling two legs a mountain.")]),
  dict(id='akupara', t='Ask the tortoise, he is older', a='Kurmasana · Primary. The crane (baka) is Bakasana · Intermediate',
   s="The story goes that a man whose good deeds were forgotten asked the old sage Markandeya: do you know me? The sage sent him to an older owl. The owl sent him to an older crane. The crane sent him to the oldest one, the tortoise Akupara. The tortoise cried and remembered him: the cows he gave away had dug this lake with their hooves.",
   src=("Mahabharata, Vana Parva 198 (Ganguli)", "https://www.gutenberg.org/ebooks/15474"),
   j=[(12, "The sage sends him to the owl. The owl sends him to the crane. The crane sends him to the tortoise. In my shala, I'm the tortoise now. Slow, and I still can't find my glasses."),
      (39, "In the story, the oldest one in the lake is the one who remembers kindness. That's the prize of getting old. Not the years. The remembering. I remember every mat in the room. The names are a work in progress.")]),
  dict(id='bharadvaja', t='Three lifetimes, one handful', a='Bharadvajasana · Intermediate', used='Used in a script, 29 Sep',
   s="The story goes that the sage Bharadvaja studied the Vedas for three lifetimes. When he was old and tired, Indra offered him a fourth life. He said he would use it to study again. Indra showed him three shapes like mountains, took one handful from each and said: this is what you learned. The Vedas have no end.",
   src=("Taittiriya Brahmana 3.10.11 (Muir, 1868, p. 17)", "https://archive.org/details/originalsanskri12muirgoog"),
   j=[(26, "Bharadvaja studied for three lifetimes and got three handfuls. I've studied for twenty years. Actually I have one handful. Actually a pinch. Actually it's under my mat."),
      (14, "People ask why I still practise after twenty years. Honest answer: Bharadvaja did three lifetimes and was shown he had a handful. I'm not at the handful yet.")]),
  dict(id='marichi', t='The ray of light in the Big Dipper', a='Marichyasana A to D · Primary',
   s="Marichi means ray of light. He is one of the seven great sages, and in Indian star lore the seven sages are the seven stars of the Big Dipper. Marichi is a star in the handle. A very old Vedic text says the seven sages were once called the Bears.",
   src=("Monier-Williams, Sanskrit-English Dictionary (1899), p. 790; Shatapatha Brahmana 2.1.2.4", "https://www.sanskrit-lexicon.uni-koeln.de/scans/csl-apidev/getword.php?dict=mw&key=marIci&input=slp1&output=roman"),
   j=[(17, "Marichi means ray of light. In Marichyasana D, I also see stars. Different reason."),
      (3, "The seven sages were once called the Bears. People think I'm a morning person. I'm not. Before coffee, I'm the eighth bear.")]),
  dict(id='matsyendra', t='The fish who kept still and listened', a='Ardha Matsyendrasana · Intermediate',
   s="A legend, as B.K.S. Iyengar tells it. Shiva explained the secrets of yoga to Parvati on a lonely island. A fish near the shore heard everything. It listened with full attention and did not move. Shiva saw that the fish had learned yoga, sprinkled water on it, and it became Matsyendra, Lord of the Fishes, who spread yoga.",
   src=("B.K.S. Iyengar, Light on Yoga (1966), Ardha Matsyendrasana I", "https://en.wikipedia.org/wiki/Matsyendranatha"),
   j=[(10, "Good news: the first yoga student in the story was a fish. Bad news: it was a better student than me. It kept still."),
      (34, "I'm not scared of the deep twists. I'm scared of the fish. It learned all of yoga in one lesson, by keeping quiet.")]),
  dict(id='tail', t='The old monkey whose tail would not move', a='Hanumanasana · Advanced A', used='Used in a script, 4 Oct',
   s="In the Mahabharata, the strong hero Bhima finds an old monkey lying across a mountain path. The monkey says he is too old to get up, so Bhima can just move his tail aside. Bhima pulls with one hand, then both, sweating. The tail does not move. The old monkey is Hanuman, his elder brother.",
   src=("Mahabharata, Vana Parva 146 (Ganguli)", "https://www.gutenberg.org/ebooks/15474"),
   j=[(19, "The old monkey said: I'm too old to get up, just move my tail. The strongest man alive couldn't lift it. I tried the same line on my students. They lifted me. Easily."),
      (3, "People think I'm like the old monkey. Pretending to be too old to get up. I'm not pretending. It's four in the morning.")]),
  dict(id='wish', t='Live as long as the story is told', a='Hanumanasana · Advanced A',
   s="A legend from the last book of the Ramayana. Hanuman asked Rama for one wish: to stay alive for as long as people tell Rama's story. Rama hugged him and said it would be so. That is why tradition calls Hanuman a chiranjeevi, a long-lived one, still here while the story is told.",
   src=("Valmiki Ramayana, Uttara Kanda 40 (Dutt, 1894)", "https://www.gutenberg.org/files/62496/62496-h/62496-h.htm"),
   j=[(35, "Hanuman lives as long as the story is told. When I say \"Hanumanasana, next year\", I mean my splits live as long as I keep telling that story. Twenty years so far.")]),
  dict(id='jambavan', t='The old bear who could still jump ninety', a='Hanumanasana · Advanced A',
   s="In the Ramayana, the monkeys must jump across the sea: a hundred yojanas, an old unit of distance. The leaders say they can leap ten, twenty, up to eighty. Jambavan the bear, the oldest, says his strength in youth had no equal. Now he can do only ninety. Then he turns to quiet Hanuman and says: arise, leap over this ocean.",
   src=("Valmiki Ramayana, Kishkindha Kanda 65 to 66 (Hanumanta Rao)", "https://www.valmikiramayan.net/utf8/kish/sarga65/kishkindhasans65.htm"),
   j=[(39, "The old bear said: when I was young, I'd have made the jump. Now I can do ninety, not a hundred. Then he turned to the young one and said: you can. That's my job now too. Also, for the record, ninety is a lot.")]),
  dict(id='autumns', t='A hundred autumns', a='Vasisthasana · Advanced A, and every Surya Namaskara',
   s="The seventh book of the Rig Veda is credited to the sage Vasistha. One hymn has a simple wish about the rising sun: 'A hundred autumns may we see that bright eye, god-ordained, arise: A hundred autumns may we live.' An autumn here means a year. Ashtanga practice still opens by saluting the sun.",
   src=("Rig Veda 7.66.16 (Griffith, 1891)", "https://archive.org/details/hymnsrigveda01grifgoog"),
   j=[(13, "Old Vedic prayer: may we see a hundred autumns. Me, in Bangkok: may we see one autumn."),
      (36, "Longevity. Three thousand years ago it was one wish: let me see the sun come up a hundred more times. I see it come up every day. From the mat. I've been up since four.")]),
  dict(id='arundhati', t='The old couple in the sky', a='Vasisthasana · Advanced A', used='Used in a script, 8 Oct',
   s="In the Big Dipper, the sage Vasistha's star has a faint partner: Arundhati, his wife. Astronomers call them Mizar and Alcor. An old Vedic wedding guide says that when the bride sees the pole star, Arundhati and the seven sages, she breaks her silence and says: may my husband live, and may we have children.",
   src=("Asvalayana Grihya Sutra 1.7.22 (Oldenberg, SBE 29, 1886)", "https://archive.org/details/grihyastrasrul01oldeuoft"),
   j=[(38, "Vasistha's star has stood still in the sky for three thousand years. I hold Vasisthasana for five breaths and wobble on every one.")]),
  dict(id='frogs', t='The frogs who wake with the rain', a='Bhekasana · Intermediate', used='Used in a script, 9 Oct',
   s="A Rig Veda hymn sings about frogs that lie quiet for a whole year, like people keeping a vow, then wake up when the rain comes. One frog repeats another's call, 'as he who learns the lesson of the teacher.' At the end the poet thanks the frogs for the rainy season and for longer lives.",
   src=("Rig Veda 7.103 (Griffith, 1891)", "https://archive.org/details/hymnsrigveda01grifgoog"),
   j=[(17, "The old hymn thanks the frogs for longer lives. I tried Bhekasana. It made the morning longer."),
      (20, "My knees are like the frogs in the hymn. Quiet all year. Then every morning in Bhekasana, they sing.")]),
  dict(id='ananta', t='The serpent who holds the earth steady', a='The opening chant, every practice',
   s="The story goes that the serpent Shesha, also called Ananta, the endless, went away to practise until he was only skin and bone. Brahma told him his hard practice was troubling all creatures, and offered him a gift. Shesha asked only to keep loving goodness and practice. So Brahma gave him a job: hold the earth steady on his head. Tradition says Patanjali is Ananta.",
   src=("Mahabharata, Adi Parva 36 (Ganguli); Yoga Sutra 2.47 (Woods, 1914)", "https://www.gutenberg.org/ebooks/15474"),
   j=[(9, "The serpent practised so hard, all creatures felt it. I practise so hard, the neighbours feel it. Through the wall. It's the breathing."),
      (40, "Patanjali says asana is steady and easy. Practise like that. Not hard enough to trouble the world. Just hard enough to trouble your hamstrings.")]),
  dict(id='gonika', t='The old teacher and the joined palms', a='The opening chant, every practice',
   s="A legend. The yogini Gonika felt her life was near its end, with no one to pass her knowledge to. She prayed to the sun, water cupped in her palms. When she opened her eyes, a tiny snake lay there. It took human form and asked to be her son. She named him Patanjali: pata, fallen, anjali, joined palms.",
   src=("B.K.S. Iyengar, 'Legend of Sage Patanjali', bksiyengar.com", "https://bksiyengar.com/modules/iyoga/legend.htm"),
   j=[(39, "Every old teacher knows Gonika's prayer: who do I pass this to? Her answer fell into her joined palms. Mine walk in at six in the morning. Most of them are already better than me."),
      (37, "I've joined my palms for the opening chant for twenty years. Gonika got Patanjali. The only thing that ever fell into mine was my glasses.")]),
  dict(id='lakh', t='8,400,000 asanas, one for every creature', a='Kurmasana, Kukkutasana · Primary. Bhekasana, Bakasana, Mayurasana · Intermediate',
   s="An old yoga text, the Gheranda Samhita, says Shiva described 8,400,000 asanas, as many as there are kinds of living creatures. Of these, 84 are the best, and 32 are useful for people. Maybe that is why so many asanas carry animal names: tortoise, rooster, frog, crane, peacock, fish.",
   src=("Gheranda Samhita 2.1 to 2.2 (Vasu, 1914)", "https://archive.org/details/india.history.resource.88861"),
   j=[(38, "8,400,000 asanas. At one new asana a day, I finish in about 23,000 years. With my hamstrings, add a thousand.")]),
  dict(id='makaranda', t='7,000, then 700, then 84', a='Where the Ashtanga series come from',
   s="In his 1934 book Yoga Makaranda, Krishnamacharya wrote about great teachers of the past who knew thousands of asanas. His own teacher in Nepal, Ramamohana Brahmachari, had mastered 7,000, he wrote, and with his teacher's guidance he mastered 700. The books of his day, he added, showed only 84.",
   src=("T. Krishnamacharya, Yoga Makaranda (1934), ch. 2.2 (tr. Ranganathan, 2006)", "https://terebess.hu/english/Yoga-Makaranda.pdf"),
   j=[(12, "His teacher: 7,000. Him: 700. The books: 84. Me, after twenty years: one I've truly mastered. Getting up at four.")]),
 ]),
 ('Long-life legends from India', [
  dict(id='markandeya', t='Thousands of years old, looks twenty-five', a='No asana link',
   s="In the Mahabharata, the sage Markandeya arrives 'grown grey in the practise of penances'. He 'had seen many thousand years of life', yet 'signs of old age he had none'. In fact, 'he looked like one only twenty-five years old'.",
   src=("Mahabharata, Vana Parva 182 (Ganguli)", "https://www.gutenberg.org/ebooks/15474"),
   j=[(24, "The old book says Markandeya went grey from practice and still looked twenty-five. In my head, that's me. In the mirror, I've done the first half.")]),
  dict(id='lomasha', t='The hermit called Hairy', a='No asana link',
   s="An Indian story tells of a hermit named Lomasha, Hairy. His chest hair grew in a ring, bare in the middle, because one hair falls each time a whole era of the gods ends. Still feeling short-lived, he chose 'to possess no home, to build no house', and carried only an umbrella of grass.",
   src=("Brahmavaivarta Purana, retold in Heinrich Zimmer, Myths and Symbols in Indian Art (1946), pp. 8 to 9", "https://archive.org/details/in.ernet.dli.2015.28989"),
   j=[(20, "My hamstrings open the way Lomasha's hair falls. One per age of the world. Twenty years in, the first age hasn't ended.")]),
  dict(id='bhusunda', t='The old crow who watched his breath', a='No asana link. The breath in every vinyasa',
   s="The Yoga Vasishtha tells of Bhusunda, an old crow in a wish-granting tree on Mount Meru. He was 'beauteous even in old age', and no one had lived longer. His secret, he said, was watching his breath. Following every inhale and exhale, he found his life as endless as his breathing.",
   src=("Yoga Vasishtha, Book VI, ch. 14 and 24 (Mitra)", "https://www.gutenberg.org/ebooks/46531"),
   j=[(6, "The oldest crow in the old book was asked for his secret. He said: watch the breath. Terrible secret. Free, and nobody wants it."),
      (19, "The crow found his breath endless. Mine feels endless too. In Navasana. Round five.")]),
  dict(id='chyavana', t='Pick your age: the pool and the jam', a='No asana link',
   s="In an old Vedic story, the sage Chyavana was very old and weak. The healer twins, the Ashvins, told his wife to take him into a pool, 'and he shall come forth with whatever age he shall desire'. He did. A later Ayurveda text, the Charaka Samhita, also credits a herbal jam with his youth: Chyavanaprash.",
   src=("Shatapatha Brahmana 4.1.5 (Eggeling, SBE 26); Charaka Samhita, Chikitsa 1.1.72", "https://sacred-texts.com/hin/sbr/sbe26/sbe2644.htm"),
   j=[(30, "Chyavana got young again two ways, depending on the book: a swim in a pool, or a spoon of herbal jam. You can have one or the other. My knees want both."),
      (21, "I'll be honest. If I got Chyavana's pool, I wouldn't ask for youth. Just hamstrings that reach my toes before seven.")]),
  dict(id='heap', t='The master found on a dung heap', a='Goraksha asana (Bhadrasana), close to Baddha Konasana · Primary',
   s="A legend from Nepal. Shiva gave a woman something to eat and promised her a son. She threw it on a dung heap. Twelve years later the sage Matsyendra came by and asked to see the child. She searched the heap and found a boy of twelve. He became Gorakhnath, Matsyendra's loyal student.",
   src=("G. W. Briggs, Gorakhnath and the Kanphata Yogis (1938), pp. 182 to 183", "https://archive.org/details/in.ernet.dli.2015.170504"),
   j=[(38, "Gorakhnath took twelve years to show up. I've given my hamstrings twenty. They still haven't.")]),
  dict(id='ages', t='The teacher who shows up in every age', a='Goraksha asana, close to Baddha Konasana · Primary',
   s="A belief recorded in 1938: in many places, Gorakhnath is seen as a teacher 'outside of the ordinary laws of time'. It is said he appeared on earth in each of the four world-ages, in a different place each time.",
   src=("G. W. Briggs, Gorakhnath and the Kanphata Yogis (1938), pp. 228 to 229", "https://archive.org/details/in.ernet.dli.2015.170504"),
   j=[(27, "I don't like to brag. Gorakhnath showed up in four ages of the world. I show up six mornings a week. One of us is a legend. The other one is just early.")]),
  dict(id='tirumular', t='One verse a year for 3,000 years', a='Padmasana is one of the seven chief asanas he names',
   s="The story goes that the Tamil yogi Tirumular sat in meditation under a pipal tree. Once a year he came out to write one verse. After 3,000 years he had the Tirumantiram, a classic of Tamil yoga. Scholars date the book much later. It names seven chief asanas, including Padma, the lotus.",
   src=("Sekkizhar, Periya Puranam (12th c.); Tirumantiram, Tantra 3", "https://archive.arunachala.org/docs/periya-p/tirumoola"),
   j=[(22, "Tirumular wrote one verse a year. Today I posted one Reel. At his speed, I'm a year ahead by lunch. Someone bring a cake."),
      (10, "Good news: I'm as steady as Tirumular. Bad news: at his speed, my hamstrings open in the year 5026.")]),
 ]),
 ('Around the world', [
  dict(id='pengzu', t='Pengzu, 800 years of stretching and breathing', a='No asana link. China',
   s="The story goes that Pengzu, an official in ancient China, lived more than 800 years. An old book of immortals says he often ate a fine fungus called zhi and was 'good at daoyin and moving qi': guided stretching and breathing. His name became China's word for long life.",
   src=("Liexian zhuan, entry 'Pengzu' (1st c. BCE)", "https://www.gutenberg.org/ebooks/25414"),
   j=[(33, "The old book on Pengzu: over 800 years, ate fine mushrooms, good at stretching and breathing. I have one of the three. It's not the 800 years.")]),
  dict(id='zhuangzi', t='Hang like a bear, stretch like a bird', a='No asana link. China',
   s="Zhuangzi, chapter 15, describes people who breathe out the old and in the new, hang like a bear and stretch like a bird, hoping to live as long as Pengzu. Then it says the sage reaches long life without these exercises, through calm and stillness. A silk chart buried in 168 BCE labels one figure 'bear hang'.",
   src=("Zhuangzi ch. 15 'Keyi' (Legge, SBE 39, 1891, p. 364)", "https://archive.org/details/wg939"),
   j=[(21, "I'll be honest. Zhuangzi wrote about people who hang like bears and stretch like birds to live long. That's me. He said the wise one gets there by being calm. I'm still on the stretching part. The calm doesn't get up at four.")]),
  dict(id='huatuo', t='A door hinge never rots', a='No asana link. China', used='Used in a carousel, 9 Oct',
   s="The doctor Hua Tuo told his student Wu Pu that the body wants work, but never to the extreme. Moving keeps the blood flowing, 'like a door hinge that never rots'. He taught the Five Animal Frolics: tiger, deer, bear, ape and bird. An old history records that Wu Pu, past ninety, had sharp ears and eyes and firm teeth.",
   src=("Sanguozhi, juan 29, biography of Hua Tuo", "https://zh.wikisource.org/wiki/三國志/卷29"),
   j=[(20, "A body is like a door hinge, said Hua Tuo. Move it and it never rots. My hinges move every day. They also squeak."),
      (33, "Hua Tuo: do the animal exercise until you sweat a little, then dust yourself with powder. In Bangkok, a little sweat is the walk to the shala. I go straight to the powder.")]),
  dict(id='zhangguo', t='The immortal who folded his donkey', a='No asana link. China',
   s="The story goes that Zhang Guo, later counted among the Eight Immortals, rode a white donkey that went tens of thousands of li a day. At rest he folded it thin as paper and put it in a box. To ride, he sprayed it with water. Elders said that when they were children, he already claimed to be several hundred years old.",
   src=("Taiping guangji, juan 30, 'Zhang Guo' (978)", "https://zh.wikisource.org/wiki/太平廣記/卷第030"),
   j=[(5, "Zhang Guo could fold his donkey flat as paper and put it in a box. I can't fold my mat on the first try.")]),
  dict(id='dufu', t='"Seventy is rare" was about spring', a='No asana link. China',
   s="Chinese people call age seventy guxi, rare since ancient times. It comes from a spring poem by Du Fu, written in 758: 'I have wine debts everywhere I go; since ancient times, few live to seventy.' The poem means: enjoy spring now. It was never a health fact. China's average life expectancy reached 79.25 years in 2025.",
   src=("Du Fu, 'Qujiang', poem 2 (758); National Health Commission of China, 2025 bulletin", "https://www.stdaily.com/web/gdxw/2026-08/28/content_571589.html"),
   j=[(33, "Du Fu wrote: since old times, few live to seventy. Read the line before it: he owed money at every wine shop. It's a spring poem about enjoying life. It was never about my knees.")]),
  dict(id='tithonus', t='Tithonus: forever, but no youth', a='No asana link. Greece',
   s="In a Greek myth, the dawn goddess Eos loved a man named Tithonus. She asked Zeus to let him live forever, but she did not think to ask for youth. He grew so old he 'could not move nor lift his limbs'. She laid him in a room behind shining doors. Later tellings turn him into a cicada.",
   src=("Homeric Hymn to Aphrodite, lines 218 to 238 (Evelyn-White, 1914)", "https://www.perseus.tufts.edu/hopper/text?doc=Perseus:text:1999.01.0138:hymn=5"),
   j=[(10, "Good news: Tithonus got to live forever. Bad news: nobody asked for the knees."),
      (40, "Long life without a body that moves is the oldest bad deal in the books. Ask for both. Then practise. Nobody does the second part for you.")]),
  dict(id='urashima', t="Urashima and the box", a='Kurmasana, Supta Kurmasana · Primary. Japan',
   s="This Japanese legend is over 1,300 years old. A fisherman named Urashima meets a turtle and is taken to a palace under the sea. After a short stay he goes home, but 300 years have passed. He opens a box he was told never to open. White smoke rises, and he becomes an old man.",
   src=("JAANUS, Columbia University, 'Urashima' (Tango fudoki, 713)", "https://projects.mcah.columbia.edu/jaanus/record/urashima"),
   j=[(20, "Supta Kurmasana is like Urashima's trip. A few minutes with a turtle. You come out 300 years older.")]),
  dict(id='crane', t='Crane 1,000 years, turtle 10,000', a='Bakasana · Intermediate. Kurmasana · Primary. Japan',
   s="Japanese people say: the crane lives 1,000 years, the turtle 10,000. The crane part comes from the Chinese book Huainanzi. The turtle part may have been added in Japan. In one old storybook, Urashima does not stay old. He becomes a crane, and he and the sea woman, who was the turtle, are honoured together as gods.",
   src=("Huainanzi ch. 17; National Diet Library, 'Hon no Mangekyo' no. 36", "https://www.ndl.go.jp/kaleido/entry/36/2.html"),
   j=[(38, "The crane lives a thousand years, the turtle ten thousand. In Bakasana I'm a crane for four seconds. In Supta Kurmasana I'm a turtle for ten thousand years. I can't get out.")]),
  dict(id='ilya', t='Ilya of Murom gets up', a='Utthita Hasta Padangusthasana · Primary (theme only). Russia',
   s="In a Russian folk tale, Ilya of Murom could not use his arms or legs for thirty years. Two wandering pilgrims asked him to fetch them a cup. He lifted an arm, stretched a leg, and stood. After one cup he said he could turn the earth over. Too much, they said, and a second cup halved it.",
   src=("M. M. Korguev, 'Ilya Muromets' (1939), Russian Wikisource", "https://ru.wikisource.org/wiki/Илья_Муромец_(Коргуев)"),
   j=[(39, "Russia's great hero started late. Thirty years without moving, then one arm, one leg, then up. My students who start at 45 are early."),
      (38, "Ilya's legs woke up after thirty years. My hamstrings are on year twenty. Ten more, and I reach my toe.")]),
  dict(id='ruesi', t='Ruesi dat ton: the hermits who stretched', a="Thailand's own cousin of asana",
   s="Thai tradition says hermits, ruesi, stiff after long meditation, stretched to ease their aches. This is ruesi dat ton, the hermit bends his own body. In 1836, craftsmen at Wat Pho in Bangkok cast hermit statues in 80 positions, each with a four-line verse on stone about what it was meant to help.",
   src=("MGR Online, 23 Apr 2009; O. Chueanoi, Journal of Chandrakasemsarn 27(1)", "https://mgronline.com/qol/detail/9520000045247"),
   j=[(27, "I don't like to brag. Bangkok has had a stretching manual in metal and stone since 1836. Eighty verses. Twenty years in, I'm on verse one.")]),
  dict(id='ponce', t='The man who never looked for the Fountain of Youth', a='No asana link',
   s="Many people learn that the explorer Juan Ponce de León sailed to Florida in 1513 to find the Fountain of Youth. Historians say no paper from his lifetime links him to a fountain. His contracts talk about finding new islands. A writer first tied him to it in 1535, twenty-two years after the voyage.",
   src=("History.com, 2 Apr 2013; Smithsonian Magazine, June 2013", "https://www.history.com/articles/the-myth-of-ponce-de-leon-and-the-fountain-of-youth"),
   j=[(11, "The Fountain of Youth has three problems. Nobody found it. The explorer never looked for it. And the real one opens at six a.m., on a mat.")]),
 ]),
]

# Myth vs fact: m = the myth or the old promise, f = what is true.
B_GROUPS = [
 ('Old book promises', [
  dict(id='grey', t='Six months upside down, goodbye grey hair', a='Sirsasana, Sarvangasana · Finishing. The book means Viparita Karani',
   m="The Hatha Yoga Pradipika says: head on the ground, feet to the sky, 'for a second only the first day, and increase this time daily.' Then: 'After six months, the wrinkles and grey hair are not seen.'",
   f="The first line is great coaching. No study has tested the second. In a Columbia study of 14 people, a few grey hairs got their colour back when stress went down, once after a holiday. It did not test yoga.",
   src=("Hatha Yoga Pradipika 3.80 to 3.81 (Sinh, 1914); Rosenberg et al., eLife 2021", "https://www.cuimc.columbia.edu/news/its-true-stress-does-turn-hair-gray-and-its-reversible"),
   j=[(7, "How long until the grey goes? The old book says six months. The new study says one holiday. I teach six mornings a week. I'll never know.")]),
  dict(id='sixteen', t='The old man who becomes sixteen', a='Mula Bandha, Uddiyana Bandha · every series',
   m="The Hatha Yoga Pradipika promises youth from the bandhas. With Mula Bandha, 'even an old man becomes young'. One breath practice makes you young, 'as it were 16 years old'.",
   f="Nobody turns sixteen. But at the Mayo Clinic, 12 weeks of interval training raised the energy power of muscle cells by 69% in people aged 65 to 80. Old muscle still answers training.",
   src=("Hatha Yoga Pradipika 2.47, 3.64 (Sinh, 1914); Robinson et al., Cell Metabolism 2017", "https://sacred-texts.com/hin/hyp/hyp04.htm"),
   j=[(37, "Twenty years of Mula Bandha and I'm still not sixteen. The only part of me acting like a teenager is my hamstrings. Stiff, stubborn, and not listening to the teacher.")]),
  dict(id='peacock', t='The peacock that digests poison', a='Mayurasana · Intermediate',
   m="The Hatha Yoga Pradipika says Mayurasana removes all diseases, digests too much bad food, and destroys kalakuta. In legend, kalakuta is the poison that rose when the ocean was churned. Shiva held it in his throat to protect the world.",
   f="No study has tested this. Enjoy the arm balance. Keep away from poison.",
   src=("Hatha Yoga Pradipika 1.31 (1.33 in Sinh, 1914)", "https://sacred-texts.com/hin/hyp/hyp03.htm"),
   j=[(17, "The old book says the peacock digests even the world's worst poison. I've tested my peacock on som tam from my street. Som tam won.")]),
  dict(id='stages', t='Sweat, tremble, hop like a frog, walk on air', a='Utpluthih · Finishing (theme only)',
   m="The Shiva Samhita lists the stages of breath practice. First the body sweats. Then it trembles. Then the yogi jumps about 'like a frog'. Later, the text says, he walks in the air.",
   f="These are the old text's words about pranayama, not a plan for your Tuesday. Nobody walks on air. Tell it as a legend.",
   src=("Shiva Samhita 3.40 to 3.46 (Vasu, 1914)", "https://archive.org/details/TheSivaSamhita"),
   j=[(12, "Stage one: sweat. Stage two: tremble. Stage three: hop like a frog. Stage four: walk on air. In Bangkok I get stage one before I unroll the mat. Twenty years in, I've reached the frog. I'm staying there.")]),
 ]),
 ('What people believe about age', [
  dict(id='young', t='Ashtanga is only for the young', a='Every series, from Surya Namaskara A',
   m="Ashtanga is for twenty-year-olds.",
   f="The Hatha Yoga Pradipika, about 600 years old: 'Whether young, old or too old, sick or lean, one who discards laziness, gets success if he practises Yoga.' Age is not the test. The only person the verse leaves out is the lazy one.",
   src=("Hatha Yoga Pradipika 1.66 (Sinh, 1914)", "https://sacred-texts.com/hin/hyp/hyp03.htm"),
   j=[(40, "Start at any age. The old book leaves out only one person: the lazy one. Don't be him. He's very comfortable, and he's not in the book.")]),
  dict(id='ninety', t='Too old to build muscle', a='Utkatasana · Surya Namaskara B (theme only)', used='Used in a carousel, 9 Oct',
   m="After a certain age, you can't build muscle.",
   f="In a 1990 study, ten frail nursing-home residents, average age 90 and up to 96, did eight weeks of heavy leg training. In the nine who finished, strength rose 174% on average, thigh muscle grew 9%, and walking speed improved 48%.",
   src=("Fiatarone et al., JAMA 1990;263(22):3029", "https://pubmed.ncbi.nlm.nih.gov/2342214/"),
   j=[(28, "I asked my legs if they're too old to get stronger. They said yes. Then I showed them this study. Average age ninety. They've stopped talking to me.")]),
  dict(id='midlife', t='Too late to start in midlife', a='Surya Namaskara A, the first thing a beginner learns',
   m="If you didn't exercise young, it's too late.",
   f="A US study of 315,059 adults: people inactive for most of adult life who became active at 40 to 61 had a 35% lower risk of dying during the study than the always inactive. The most active lifelong group: 36%. Almost the same.",
   src=("Saint-Maurice et al., JAMA Network Open 2019;2(3):e190355", "https://doi.org/10.1001/jamanetworkopen.2019.0355"),
   j=[(38, "People who started in their forties ended up almost level with the lifelong ones. 35% against 36%. I've set my alarm for four for twenty years. For one percent.")]),
  dict(id='liftmor', t="Older women shouldn't lift heavy", a='Chaturanga Dandasana (body weight, theme only)',
   m="Women with weak bones should not lift heavy.",
   f="In Australia's LIFTMOR trial, 101 women around 65 with low bone mass were split in two. One half lifted heavy, with a coach, twice a week for 8 months. Their spine bone density rose 2.9%. The gentle home group lost 1.2%. Only with a qualified coach and a doctor's OK.",
   src=("Watson et al., J Bone Miner Res 2018;33(2):211", "https://doi.org/10.1002/jbmr.3284"),
   j=[(5, "I can teach fifty people Chaturanga. I cannot pick up my own mat with straight legs.")]),
  dict(id='bedrest', t="Unfit? It's just age", a='Savasana (theme only)', used='Used in a carousel, 9 Oct',
   m="Losing fitness is just age.",
   f="In 1966, five healthy 20-year-old men in Dallas stayed in bed for three weeks. Their aerobic fitness fell 27%. Thirty years of ageing later cost them about 11%. Bed did more harm than birthdays. Six months of training brought them back to their 1966 starting level.",
   src=("McGuire et al., Circulation 2001; Mitchell et al., Circulation 2019", "https://pmc.ncbi.nlm.nih.gov/articles/PMC6814251/"),
   j=[(14, "People ask why I still get up at four. Honest answer: three weeks in bed did more harm than thirty years of birthdays. That's science. My body still votes for the bed.")]),
  dict(id='steps', t='10,000 steps is a medical rule', a='Samasthitih (Ashtanga counts breaths, not steps)',
   m="You need 10,000 steps a day.",
   f="The goal likely came from a 1965 Japanese pedometer named manpo-kei, 10,000-step meter. In a Harvard study of 16,741 women, average age 72, about 4,400 steps a day was linked to a 41% lower death rate than 2,700, with the benefit levelling off near 7,500.",
   src=("Lee et al., JAMA Intern Med 2019;179(8):1105", "https://pmc.ncbi.nlm.nih.gov/articles/PMC6547157/"),
   j=[(36, "Ten thousand steps. A pedometer name from 1965. Not a doctor in sight.")]),
  dict(id='fat', t='Muscle turns into fat', a='Utthita Hasta Padangusthasana · Primary (theme only)',
   m="Stop training and your muscle turns into fat.",
   f="In a 2007 study, 18 young adults kept one leg off the ground for four weeks. Thigh muscle shrank 7.4%, while fat between the muscles grew 14.5%. Two different tissues moved in opposite directions. Muscle did not become fat.",
   src=("Manini et al., Am J Clin Nutr 2007;85(2):377", "https://doi.org/10.1093/ajcn/85.2.377"),
   j=[(17, "They say use it or lose it. True. But muscle doesn't turn into fat. It just moves out. The fat moves into the empty room.")]),
  dict(id='flex60', t='Flexibility is gone for good after 60', a='Paschimottanasana · Primary',
   m="After sixty, stiffness is for life.",
   f="A 2019 review of 22 trials in adults with an average age of 60 or more found that yoga, compared with no exercise, improved lower-body flexibility, balance and leg strength. Moderate gains, not miracles. The body still answered practice.",
   src=("Sivaramakrishnan et al., Int J Behav Nutr Phys Act 2019;16:33", "https://doi.org/10.1186/s12966-019-0789-2"),
   j=[(10, "Good news: research says flexibility still improves after sixty. Bad news: my hamstrings heard \"after sixty\" and decided to wait.")]),
  dict(id='balance', t='After 60, balance is just gone', a='Utthita Hasta Padangusthasana, Ardha Baddha Padmottanasana · Primary',
   m="After sixty, balance is simply gone.",
   f="A 2016 review of six trials with 307 people aged 60 and over: yoga gave a small improvement in balance and a medium improvement in mobility, getting up and moving around. The authors say we do not yet know if it prevents falls.",
   src=("Youkhana et al., Age and Ageing 2016;45(1):21", "https://pubmed.ncbi.nlm.nih.gov/26707903/"),
   j=[(24, "In my head I put on my socks standing on one leg. In the mirror I'm sitting down and calling it mindfulness.")]),
  dict(id='floor', t='Getting up off the floor means nothing', a='Every seated vinyasa, and Utpluthih (theme only)',
   m="Sitting down and standing up from the floor is just a party trick.",
   f="Researchers in Brazil scored 2,002 adults aged 51 to 80 on sitting down and standing up with no help from hands or knees, 0 to 10. Over about six years, each extra point was linked to 21% better survival.",
   src=("Brito et al., Eur J Prev Cardiol 2014;21(7):892", "https://doi.org/10.1177/2047487312471759"),
   j=[(36, "Longevity test. Sit on the floor. Stand up. No hands. That's the whole test. I take it every morning. Out loud.")]),
  dict(id='invert', t='No upside down after 50', a='Sirsasana, Halasana · Finishing; Downward Dog',
   m="After fifty, going upside down turns dangerous.",
   f="In a 2006 study of 75 yoga practitioners, headstand doubled eye pressure, and age did not predict how much. In a small 2015 study, Downward Dog raised it the most of four head-down asanas, back to normal two minutes after sitting up. Glaucoma or high blood pressure? Ask your eye doctor first.",
   src=("Baskaran et al., Ophthalmology 2006; Jasien et al., PLOS ONE 2015", "https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0144505"),
   j=[(35, "When I call Downward Dog a resting asana, I mean my eyes disagree. In the study it raised eye pressure more than Halasana.")]),
 ]),
 ('What people believe about yoga and exercise', [
  dict(id='flexstart', t='You have to be flexible to start', a='Paschimottanasana · Primary; Uttanasana in Surya Namaskara',
   m="You must be flexible before you start yoga.",
   f="Patanjali's Yoga Sutra 2.46 defines asana as 'stable-and-easy posture'. Toes are not mentioned. In a 2016 trial, 118 inactive adults, average age 62, did hatha yoga three times a week for 8 weeks. Their flexibility improved, about as much as a stretching and strength group.",
   src=("Yoga Sutra 2.46 (Woods, 1914); Gothe and McAuley, J Gerontol A 2016", "https://pmc.ncbi.nlm.nih.gov/articles/PMC5864160/"),
   j=[(26, "Patanjali's definition of asana never mentions toes. I checked. Twice. Then I tried to reach mine. Also twice.")]),
  dict(id='stretching', t='Yoga is just stretching', a='Chaturanga Dandasana in Surya Namaskara A and B',
   m="Yoga is only stretching.",
   f="In a small 2001 study, 10 untrained young adults did hatha yoga at least twice a week for 8 weeks. Elbow strength rose 31% and knee-muscle endurance 57%. In 2011, six trained young people doing four rounds of Sun Salutation reached 90% of their predicted maximum heart rate in round four.",
   src=("Tran et al., Prev Cardiol 2001; Mody, J Bodyw Mov Ther 2011", "https://pubmed.ncbi.nlm.nih.gov/11832673/"),
   j=[(13, "Gentle stretching, for all levels. (pause) Five Surya Namaskara later, my shirt asks for a transfer.")]),
  dict(id='sweatfat', t='Sweat means fat is melting', a='The breath with sound, in every vinyasa',
   m="The more you sweat, the more fat you burn.",
   f="Sweat is mostly water and salt. Burned fat mostly leaves through the lungs: of 10 kg lost, 8.4 kg is breathed out as carbon dioxide. Two Sydney researchers asked 150 doctors, dietitians and trainers where lost fat goes. Only three got it right.",
   src=("Meerman and Brown, BMJ 2014;349:g7257", "https://www.unsw.edu.au/newsroom/news/2018/03/when-we-lose-weight--where-does-it-go-"),
   j=[(16, "Sweat isn't fat leaving. It's water. It's salt. It's Bangkok. The fat leaves through my mouth, one breath at a time. Very slowly.")]),
  dict(id='toxins', t='A hot room sweats out toxins', a='Surya Namaskara A and B, the heat-building start',
   m="A hot, sweaty practice flushes out toxins.",
   f="A University of Ottawa team estimated that two litres of sweat carry less than a tenth of a nanogram of fat-stored pollutants. Your liver and kidneys do the cleaning. The old Hatha Yoga Pradipika says the opposite of detox: rub your sweat back into the skin to make the body strong.",
   src=("Imbeault et al., Environment International 2018; Hatha Yoga Pradipika 2.13", "https://www.nationalgeographic.com/science/article/sweating-toxins-myth-detox-facts-saunas-pollutants-science"),
   j=[(36, "Detox. Two litres of sweat, a tenth of a nanogram of pollutants, and one towel that needs a holiday.")]),
  dict(id='twists', t='Twists wring toxins out of your organs', a='Marichyasana C and D · Primary; Ardha Matsyendrasana · Intermediate',
   m="Twists squeeze toxins out of your organs like a wet towel.",
   f="Herpreet Thind, a UMass Lowell researcher on yoga and chronic disease, told Yoga Journal there is 'no scientific basis' for this. A healthy liver cleans the body without twisting. Twists still help you turn and move.",
   src=("Yoga Journal, 18 Jan 2022", "https://www.yogajournal.com/practice/does-yoga-detox-your-body/"),
   j=[(24, "In my head, twenty years of Marichyasana D wrung me clean. In the mirror I'm not cleaner. Just stiffer, from a new angle.")]),
  dict(id='nopain', t='No pain, no gain', a='Navasana · Primary',
   m="If you're not sore, it didn't work.",
   f="In a 2016 study, ten young men trained their legs for ten weeks. Muscle damage was highest in week one but did not predict growth. Soreness is a poor scorecard. Sharp pain or joint pain is a stop sign, not progress.",
   src=("Damas et al., J Physiol 2016", "https://pmc.ncbi.nlm.nih.gov/articles/PMC5023708/"),
   j=[(17, "They say no pain, no gain. I've been sore after Navasana for twenty years. By that rule I'd be a bodybuilder. I'm a man whose legs still won't straighten in the boat.")]),
  dict(id='light', t='Only hard, sweaty exercise counts', a='Surya Namaskara A, the first step (theme only)',
   m="Gentle movement doesn't count.",
   f="A 2019 BMJ study of 36,383 adults, average age 63, wearing activity trackers: people in the top quarter for light movement had a 62% lower risk of early death than the bottom quarter. The biggest gain came from the first step up.",
   src=("Ekelund et al., BMJ 2019;366:l4570", "https://doi.org/10.1136/bmj.l4570"),
   j=[(22, "Science says the first hour of light movement does the most good. Today I did mine before six. Looking for my glasses. Someone bring a cake.")]),
  dict(id='stretchfirst', t="Stretch first and you won't get hurt", a='Padangusthasana, Padahastasana · standing',
   m="A quick stretch before exercise prevents injury.",
   f="A 2014 review of 25 trials and 26,610 people found stretching made no real difference to sports injuries. Strength training cut them to under a third. Stretching still helps range of motion. It just isn't armour.",
   src=("Lauersen et al., Br J Sports Med 2014;48(11):871", "https://doi.org/10.1136/bjsports-2013-092538"),
   j=[(13, "Stretch first and you won't get hurt. (pause) I've stretched my hamstrings every morning for twenty years. They still haven't heard.")]),
  dict(id='head', t='In headstand, the head just rests', a='Sirsasana · Finishing',
   m="In headstand, the arms do the work and the head just rests.",
   f="A 2015 study measured 45 practitioners aged 18 to 60. At peak moments the head carried 40 to 48% of body weight. Lifting up with straight legs together tended to load the neck more slowly and more evenly than bent-leg entries.",
   src=("Hector and Jensen, J Bodyw Mov Ther 2015;19(3):434", "https://pubmed.ncbi.nlm.nih.gov/26118514/"),
   j=[(21, "I'll be honest. In Sirsasana my head carries almost half my weight. It's the hardest work it does all day.")]),
  dict(id='gentle', t="Yoga is gentle, so it can't hurt", a='No single asana',
   m="Yoga is too gentle to hurt anyone.",
   f="US emergency rooms saw an estimated 29,590 yoga injuries from 2001 to 2014, most often to the trunk, and the rate was higher in people 65 and over. A 2015 review of the 94 trials that reported side effects found yoga about as safe as usual care and exercise.",
   src=("Swain and McGwin, Orthop J Sports Med 2016; Cramer et al., Am J Epidemiol 2015", "https://pmc.ncbi.nlm.nih.gov/articles/PMC5117171/"),
   j=[(40, "Yoga can hurt you. So can stairs. Warm up, go slow, tell your teacher about old injuries. Then come back tomorrow. That's the whole safety plan.")]),
  dict(id='pain', t='Yoga either fixes pain or causes it', a='Downward Dog, Chaturanga in Surya Namaskara',
   m="Yoga either fixes pain or causes it.",
   f="A one-year study of 354 people from two yoga studios found both. 10.7% got new pain from yoga, mostly in the shoulder, elbow, wrist and hand. Yet 74% said yoga improved pain they already had. Tell your teacher about injuries before class.",
   src=("Campo et al., J Bodyw Mov Ther 2018;22(2):418", "https://www.sydney.edu.au/news-opinion/news/2017/06/28/yoga-more-risky-for-causing-musculoskeletal-pain-than-you-might-.html"),
   j=[(16, "My hamstrings weren't stiff. They were concrete. Twenty years later they're softer concrete. I count that in the 74%.")]),
 ]),
]

START_A = ['tail', 'akupara', 'bharadvaja', 'jambavan', 'tithonus']
START_B = ['midlife', 'bedrest', 'ninety', 'floor', 'young']
