'use strict';
// Ashtanga Yoga Bangkok — Class Booking — generated by Hermes.
const express = require('express');
const fs = require('fs');
const path = require('path');

const app = express();
const PORT = process.env.PORT || 5000;
const CLASSES = JSON.parse(fs.readFileSync(path.join(__dirname, 'classes.json'), 'utf8'));
const BOOKINGS_FILE = path.join(__dirname, 'bookings.json');

app.use(express.json());
app.use(express.static(path.join(__dirname, 'public')));

function readBookings() {
  try { return JSON.parse(fs.readFileSync(BOOKINGS_FILE, 'utf8')); }
  catch { return []; }
}
function writeBookings(list) {
  fs.writeFileSync(BOOKINGS_FILE, JSON.stringify(list, null, 2) + '\n');
}

app.get('/api/classes', (req, res) => res.json(CLASSES));
app.get('/api/bookings', (req, res) => res.json(readBookings()));

app.post('/api/bookings', (req, res) => {
  const { name, email, classId, date } = req.body || {};
  if (!name || !email || !classId || !date) {
    return res.status(400).json({ error: 'name, email, classId and date are required' });
  }
  const klass = CLASSES.find((c) => c.id === classId);
  if (!klass) return res.status(400).json({ error: 'unknown class' });

  const bookings = readBookings();
  const taken = bookings.filter((b) => b.classId === classId && b.date === date).length;
  if (taken >= klass.capacity) {
    return res.status(409).json({ error: 'this class is full on ' + date });
  }

  const booking = { id: 'b_' + Date.now().toString(36), name, email, classId, date, createdAt: new Date().toISOString() };
  bookings.push(booking);
  writeBookings(bookings);
  res.status(201).json({ booking });
});

app.listen(PORT, () => console.log('Ashtanga Yoga Bangkok booking app on http://localhost:' + PORT));
