TH='fonts/anuphan-th.ttf'
# (photo, who, text, meaning, extra)  extra: s = story (no outer quote marks), pre = Thai line
B1=('SEEK THE TEACHER',[
('8-119',"Book of Rites (Liji), Qu Li I, tr. James Legge, 1885",
 "I have heard ... of (scholars) coming to learn; I have not heard of (the master) going to teach.",
 "Go to the teacher. The teacher will not come to you.",{}),
('8-004',"Han Yu · On the Teacher, about 802, tr. Shih Shun Liu, 1977",
 "In ancient times scholars always had teachers... Since man is not born with knowledge, who can be without doubt? But doubt will never be resolved without a teacher.",
 "No one is born knowing. Long ago, every learner found a teacher to clear their doubts.",{}),
('8-012',"Bhagavad Gita 4.34 · tr. K. T. Telang, 1882",
 "...you should learn by salutation, question, and service. The men of knowledge who perceive the truth will teach knowledge to you.",
 "Bow, ask good questions, and help. Then the people who know will teach you.",{}),
('8-027',"Xuanzang, monk, 7th century · Huili, The Life of Hiuen-Tsiang, tr. Samuel Beal, 1888",
 "The monk Xuanzang found that China's teachers and books disagreed, so he went to India. At Nalanda he told the teacher Silabhadra: ‘I am come from the country of China, desiring to learn from your instruction...’",
 "His teachers did not agree, so he travelled all the way to India to find the right one.",{'s':1}),
('8-103',"Zeno of Citium · Diogenes Laertius, Lives VII.2-4, tr. R. D. Hicks, 1925",
 "Zeno, then thirty, read about Socrates in an Athens bookshop and asked where such men could be found. Crates passed by, and the bookseller said: ‘Follow yonder man.’ Zeno studied with teachers for twenty years.",
 "He asked where a real teacher was. One walked by, and he followed.",{'s':1}),
('8-111',"J. S. Bach · Obituary, 1754; his words to the Arnstadt council, 1706, in Spitta, tr. 1884",
 "In 1705 the organist J. S. Bach, 20, got four weeks off and walked hundreds of kilometres to Lübeck to hear Buxtehude. He stayed away four months, ‘to learn thoroughly one or two things connected with his art.’",
 "If the best teacher is far away, go to him, even on foot.",{'s':1}),
('8-142',"Michael Faraday · his notes, in Bence Jones, The Life and Letters of Faraday, 1870",
 "In 1812 Michael Faraday, 21, a bookbinder, longed for science. ‘I wrote to Sir Humphry Davy, sending, as a proof of my earnestness, the notes I had taken of his last four lectures.’ By 1813 he was Davy's assistant.",
 "Do not wait to be picked. Show your hard work and ask to learn.",{'s':1}),
('8-144',"Japanese proverb",
 "Rather than spend three years studying hard, better to spend three years choosing a teacher.",
 "The right teacher is worth more than years of studying alone.",{}),
('8-160',"Thai saying · Sit mi khru",
 "A student who has a teacher.",
 "When someone is really good, Thai people say: they had a good teacher.",{'pre':'ศิษย์มีครู'}),
('8-017',"K. Pattabhi Jois · as told by Eddie Stern, foreword to Yoga Mala, 2010",
 "In 1927, twelve-year-old Pattabhi Jois watched T. Krishnamacharya's demonstration in Hassan. The next day he rose early, went to the yogi's house and asked to be taught. He was told to come back the next day.",
 "A 12-year-old asked to learn the very next day. He grew up to teach the Ashtanga we practise.",{'s':1}),
])
B2=('IT WAS NOT EASY',[
('8-158',"Aristotle · as told by Diogenes Laertius, Lives V.18, tr. R. D. Hicks, 1925",
 "The roots of education... are bitter, but the fruit is sweet.",
 "Learning tastes bitter at the start. Later it gives sweet fruit.",{}),
('8-052',"‘Standing in the snow at Cheng's gate’ · History of Song, juan 428, tr. from Chinese",
 "Two students found their teacher Cheng Yi sitting with his eyes closed. They stood by him and waited. When he woke, the snow outside the door was a foot deep.",
 "They waited quietly for their teacher while a foot of snow fell outside.",{'s':1}),
('8-085',"Vidura, the wise counsellor · Mahabharata, Udyoga Parva 40, tr. K. M. Ganguli, 1883-96",
 "Votaries of pleasure must give up knowledge, and votaries of knowledge must give up pleasure.",
 "You cannot have all the comfort and all the learning. To learn, give up some comfort.",{}),
('8-105',"Three Character Classic, 13th century · tr. Herbert A. Giles, 1900",
 "...one who put fireflies in a bag, and again another who used the white glare from snow. Although their families were poor, these men studied unceasingly.",
 "No money for lamp oil? One boy read by fireflies, another by snow light.",{}),
('8-120',"Cleanthes · as told by Diogenes Laertius, Lives VII.168-174, tr. R. D. Hicks, 1925",
 "Cleanthes drew water in gardens by night so he could study with Zeno by day. Too poor for paper, he wrote the lectures on oyster-shells and ox bones.",
 "He worked at night to learn by day. Later he took his teacher's place.",{'s':1}),
('8-134',"Antisthenes · Diogenes Laertius, Lives VI.2, tr. R. D. Hicks, 1925",
 "Already a teacher, Antisthenes became a pupil of Socrates. He ‘every day would tramp the five miles to Athens in order to hear Socrates.’",
 "He became a student again, and walked about 8 km to class every day.",{'s':1}),
('8-140',"Mikhail Lomonosov · letter of 10 May 1753, tr. from Russian",
 "At 19, fisherman's son Mikhail Lomonosov walked to Moscow to study. He lived on bread and kvass: ‘Thus I lived five years, and did not give up learning.’",
 "Five poor years on bread and kvass, a cheap drink. He kept studying.",{'s':1}),
('8-148',"Benjamin Franklin, printer's apprentice · Autobiography, 1771",
 "Often I sat up in my room reading the greatest part of the night, when the book was borrowed in the evening and to be returned early in the morning...",
 "He read most of the night, because the borrowed book had to go back by morning.",{}),
('8-153',"Fukuzawa Yukichi, student in Osaka, 1850s · Autobiography, tr. Eiichi Kiyooka, 1934",
 "Fukuzawa looked for his pillow: ‘I realized suddenly that I had not used one for the whole year... I had been studying without regard to day or night...’",
 "He studied day and night for a whole year and never once slept on a pillow.",{'s':1}),
('8-137',"T. Krishnamacharya · as told by his son T. K. V. Desikachar, The Heart of Yoga, 1995",
 "As his son tells it, in 1916 Krishnamacharya went to the Himalayas to find his teacher, Ramamohan Brahmachari, and stayed more than seven years.",
 "He became Pattabhi Jois's teacher. Our Ashtanga line goes back to this search.",{'s':1}),
])
B3=('THE WILL TO LEARN',[
('8-124',"Seneca · Letters 71, tr. R. M. Gummere, 1920",
 "There remains much more of the road than we have put behind us; but the greater part of progress is the desire to progress.",
 "Wanting to grow is most of growing.",{}),
('8-101',"Confucius and his student Ran Qiu · Analects VI.10, tr. James Legge, 1861",
 "Yen Ch'iu said, ‘It is not that I do not delight in your doctrines, but my strength is insufficient.’ The Master said, ‘Those whose strength is insufficient give over in the middle of the way but now you limit yourself.’",
 "The weak stop halfway. You stopped before you even started.",{}),
('8-117',"Dogen · Shobogenzo Zuimonki 2-14, tr. Shohaku Okumura, 1988",
 "It depends only on whether one's aspiration is firmly determined or not. A person who arouses true aspiration and studies as hard as his capacity allows will not fail to attain (the Way).",
 "Talent is not the key. A firm wish to learn, plus steady effort, gets you there.",{}),
('8-031',"Helen Keller · The Story of My Life, 1903",
 "...every one who wishes to gain true knowledge must climb the Hill Difficulty alone... I slip back many times, I fall, I stand still... I trudge on, I gain a little, I feel encouraged, I get more eager and climb higher...",
 "Learning is a steep hill. You slip and fall, but you keep climbing.",{}),
('8-098',"The Buddha, about his first teacher · Majjhima Nikaya 26, tr. Bhikkhu Sujato, 2018",
 "It's not just Alara Kalama who has faith, energy, mindfulness, immersion, and wisdom; I too have these things. Why don't I make an effort to realize the same teaching...?",
 "My teacher has faith and effort. So do I. Why not work and learn it too?",{}),
('8-110',"Plutarch · On Listening to Lectures 18, tr. F. C. Babbitt, 1927",
 "For the mind does not require filling like a bottle, but rather, like wood, it only requires kindling to create in it an impulse to think independently and an ardent desire for the truth.",
 "Your mind is not a bottle to fill. It is wood to light.",{}),
('8-149',"Jane Goodall, on her mother's advice · Science Friday interview, 2002",
 "...if you really want something, you work hard, you take advantage of opportunity, and you never give up.",
 "Really want it? Work hard, use every chance, and never give up.",{}),
('8-154',"Hwang Sang and his teacher Jeong Yak-yong · Imsul-gi, 1862, tr. from Korean",
 "In 1802 Hwang Sang, 15, told his teacher he had three faults: dull, blocked and slow. The answer: ‘The way to dig in? Diligence. To break through? Diligence. To polish? Diligence.’ He kept it for sixty years.",
 "Think you are too slow to learn? The answer is the same three times: keep working.",{'s':1}),
('8-157',"Russian proverb · V. I. Dal's collection, 1862",
 "Live a lifetime, learn a lifetime.",
 "Keep learning for as long as you live.",{}),
('8-167',"K. Pattabhi Jois · as told by Eddie Stern, foreword to Yoga Mala, 2010",
 "In 1930 the young Pattabhi Jois left for Mysore ‘with two rupees in his pocket’ to study Sanskrit. ‘For one or two years he begged for food and slept in the dormitory room of a friend.’ There he found his teacher again.",
 "Almost no money and no room of his own. He kept learning anyway.",{'s':1}),
])
