TH='fonts/anuphan-th.ttf'
ZH='/usr/share/fonts/truetype/wqy/wqy-zenhei.ttc'
# (photo, who, text, meaning, extra)  extra: s = story (no outer quote marks), pre = line in Thai/Chinese, pf = its font
B1=('MOVE OR RUST',[
('9-081',"Lüshi Chunqiu, Chinese classic, about 239 BCE · tr. from Chinese",
 "Flowing water does not go bad, and a door hinge is not eaten by insects, because they move. It is the same with body and qi: if the body does not move, the essence does not flow...",
 "Moving water stays fresh. A turning door hinge does not rot. A moving body stays healthy too.",{}),
('',"Russian proverb · V. I. Dal's collection, 1862",
 "Lying in one place, even a stone grows over with moss.",
 "Keep moving, or the moss grows on you too.",{}),
('',"Seneca · Letters to Lucilius 55, tr. R. M. Gummere, 1917",
 "...Nature gave us legs with which to do our own walking... Our luxuries have condemned us to weakness; we have ceased to be able to do that which we have long declined to do.",
 "Legs are made for walking. What you stop doing for a long time, you soon cannot do.",{}),
('',"Suwen (Basic Questions), Chinese medical classic, ch. 23 · tr. from Chinese",
 "Long looking harms the blood, long lying harms the qi, long sitting harms the flesh, long standing harms the bones, long walking harms the sinews.",
 "Too much of one thing, even sitting, harms the body. Mix moving and resting.",{}),
('',"Socrates, in Xenophon's Memorabilia III.12, tr. E. C. Marchant, 1923",
 "...it is a disgrace to grow old through sheer carelessness before seeing what manner of man you may become by developing your bodily strength and beauty to their highest limit... it will not come of its own accord.",
 "Don't grow old without finding out how strong your body can be. It won't happen by itself.",{}),
('',"Leo Tolstoy · What Shall We Do?, 1886, tr. Free Age Press",
 "Tolstoy told of a steward who kept a friend's best horses in the stable on oats but, afraid for them, never rode them or led them out. ‘Of course, all these horses became good for nothing.’",
 "Even the best horse gets weak if it never moves. Our bodies are the same.",{'s':1}),
('',"Kaibara Ekiken · Yojokun (Lessons on Nourishing Life), 1713 · tr. from Japanese",
 "Move the body a little every day. Do not sit still for long. After every meal, walk a few hundred steps quietly in the garden. When it rains, walk slowly inside the house, many times.",
 "Move a little every day. Walk after meals, even on rainy days.",{}),
('',"Quoted in Dongui Bogam, Korea, 1613 · tr. from classical Chinese",
 "...Whoever would nourish the arms always bends and stretches them; whoever would nourish the legs always walks.",
 "To keep your arms strong, bend and stretch them. To keep your legs strong, walk.",{}),
('',"World Health Organization · Physical activity fact sheet, 2024",
 "...any amount of physical activity is better than none; all physical activity counts; all age groups should limit the amount of time being sedentary; and muscle strengthening benefits everyone.",
 "Any movement is better than none. Sit less, and make your muscles work.",{}),
('',"Gheranda Samhita 1.8 · tr. Srisa Chandra Vasu, 1914",
 "Like unto an unbaked earthen pot thrown in water, the body is soon decayed (in this world). Bake it hard in the fire of Training in order to strengthen and purify the body.",
 "Your body is like a soft clay pot. Daily practice is the fire that makes it strong.",{}),
])
B2=('KEEPS SICKNESS AWAY',[
('9-133',"Sushruta Samhita, Chikitsa XXIV · tr. K. K. L. Bhishagratna, 1911",
 "Diseases fly from the presence of a person, habituated to regular physical exercise... just as small beasts do on seeing a lion.",
 "An old Indian medical book says: sickness runs from people who exercise, like small animals from a lion.",{}),
('',"Hua Tuo, physician, about 200 CE · Sanguozhi, tr. Victor H. Mair, 1994",
 "The human body needs exertion... but it shouldn't be pushed to the limit. Movement of the limbs... enables the blood in the arteries to flow freely, preventing sickness from occurring. It's like a door-pivot that never decays...",
 "Your body needs to move, but not until you are worn out. Moving keeps the blood flowing.",{}),
('',"Hippocratic writings · Regimen I.2, tr. W. H. S. Jones, 1931",
 "...eating alone will not keep a man well; he must also take exercise. For food and exercise, while possessing opposite qualities, yet work together to produce health.",
 "Good food alone cannot keep you healthy. You also need to move.",{}),
('',"Charaka Samhita, Sutrasthana 7.32 · tr. Jamnagar edition, 1949",
 "Lightness, capacity for work, firmness, tolerance to hardship... and stimulation of the gastric fire accrue from exercise.",
 "The old Ayurveda books say exercise makes you light, steady and strong, and helps you digest.",{}),
('',"Suwen (Basic Questions), Chinese medical classic, ch. 2 · tr. from Chinese",
 "...the sage does not treat illness that has already come, but treats it before it comes... it is like digging a well when you are already thirsty... Is that not too late?",
 "Look after your health before you get sick. Don't wait until you're thirsty to dig the well.",{}),
('',"The Buddha · Anguttara Nikaya 5.29, tr. Bhikkhu Sujato, 2018",
 "...there are five benefits of walking meditation... You get fit for traveling, fit for striving in meditation, and healthy. What's eaten, drunk, chewed, and tasted is properly digested...",
 "The Buddha said walking practice keeps you fit and well, and helps you digest food.",{}),
('',"Plutarch · Advice about Keeping Well 24, tr. F. C. Babbitt, 1928",
 "...the man who thinks to conserve his health by uselessness and ease does not differ from him who guards his eyes by not seeing, and his voice by not speaking.",
 "Sitting still won't save your health.",{}),
('',"Wat Pho hermit statues, Bangkok, 1830s · K. I. Matics, Journal of the Siam Society, 1977",
 "At Wat Pho in Bangkok, statues of hermits made in the 1830s show ‘ruesi dat ton’, Thai self-stretching exercises. Each figure was meant to ease a problem, such as stiff legs, sprained shoulders or dizziness.",
 "Thailand has its own old stretching practice for aches and stiffness.",{'s':1,'pre':'ฤๅษีดัดตน','pf':TH}),
('',"Chinese folk saying · Thomas Fuller, Gnomologia no. 6251, 1732",
 "A Chinese folk saying goes: ‘Walk a hundred steps after a meal, and live to ninety-nine.’ An English proverb book of 1732 says: ‘After Dinner, sit a while: After Supper, walk a Mile.’",
 "Two countries, same advice: after you eat, take a gentle walk.",{'s':1,'pre':'饭后百步走，活到九十九','pf':ZH,'ps':56}),
('',"B. K. S. Iyengar · Light on Life, 2005",
 "...it has to be earned through sweat.",
 "Earn your health with your own sweat.",{}),
])
B3=('WHAT SCIENCE FOUND',[
('9-127',"Dallas Bed Rest and Training Study · Circulation, 1968 and 2001",
 "In 1966, five healthy 20-year-old men spent 3 weeks in bed, which ‘had a more profound impact on physical work capacity than did 3 decades of aging.’ At 50, six months of training reversed their age-related loss of aerobic power.",
 "Three weeks in bed hurt their fitness more than 30 years of ageing. Training at 50 won it back.",{'s':1}),
('',"J. N. Morris et al. · The Lancet, 1953; Med Sci Sports Exerc, 1994",
 "In 1953 Dr Jerry Morris found London bus conductors, who climbed the double-decker stairs, had less heart disease than drivers, who sat at the wheel. In 1994 he wrote that physical activity ‘could be today's \"best buy\" in public health...’",
 "The bus workers who climbed stairs all day had healthier hearts than the drivers who sat.",{'s':1}),
('',"R. S. Paffenbarger Jr. et al. · New England Journal of Medicine, 1986",
 "Of 16,936 Harvard alumni, men who burned 2,000+ kcal a week walking, climbing stairs and playing sport had death rates ‘one quarter to one third lower’ than less active men. The study's leader, Ralph Paffenbarger, began running at 45.",
 "Men who walked, climbed stairs and played sport lived longer. The scientist himself began running at 45.",{'s':1}),
('',"C. P. Wen et al. · The Lancet, 2011",
 "A study of 416,175 adults in Taiwan (1996-2008) found that people who exercised about 15 minutes a day (92 minutes a week) had a 14% lower risk of death and a 3-year longer life expectancy than inactive people.",
 "Even about 15 minutes of exercise a day was linked to a longer life.",{'s':1}),
('',"D. A. Bennett et al., China Kadoorie Biobank · JAMA Cardiology, 2017",
 "China Kadoorie Biobank: 487,334 adults aged 30 to 79 in 10 areas of China. About one more hour of brisk walking a day went with a 6% lower risk of major heart and blood-vessel disease.",
 "In China, people who moved more each day had less heart and blood-vessel disease.",{'s':1}),
('',"X. R. Pan et al., Da Qing study · Diabetes Care, 1997",
 "In 1986, clinics in Da Qing, China, screened 110,660 people and found 577 with raised blood sugar. After 6 years, 41.1% of the exercise group had developed diabetes, against 67.7% of the control group.",
 "For people with high blood sugar, exercise lowered the chance of getting diabetes.",{'s':1}),
('',"F. Li et al. · JAMA Internal Medicine, 2018",
 "670 people aged 70 or older, who had fallen in the past year or were slow to get up and walk, took two one-hour classes a week for 24 weeks. The 224 doing tai chi had 152 falls; the 223 stretching had 363.",
 "A special tai chi class helped older people keep their balance and fall far less.",{'s':1}),
('',"M. A. Fiatarone et al. · JAMA, 1990",
 "Ten frail nursing-home residents aged about 90 did 8 weeks of strength training. The 9 who finished got on average 174% stronger and walked 48% faster.",
 "Even at 90, muscles grow stronger when you train them.",{'s':1}),
('',"N. R. Lazarus · NPR, 2018; Aging Cell, 2018",
 "At 82, Professor Norman Lazarus still cycled: ‘...I wasn't aging in the way that I'd sort of been taught in medical school.’ In his study, cyclists aged 55-79 had as many new T cells as young adults.",
 "People who kept cycling for years kept parts of their immune system young.",{'s':1}),
('',"Daniel E. Lieberman, Harvard · Exercised, 2020",
 "A mountain of evidence suggests that the Fountain of Youth runs with sweat. That sweat, moreover, needs to keep flowing as we age.",
 "Moving and sweating help keep you young. Keep doing it as you grow older.",{}),
])
B4=('FIT WHEN OLD',[
('9-055',"Hippocratic Aphorisms II.49 · tr. Francis Adams, 1849",
 "Those who are accustomed to endure habitual labors, although they be weak or old, bear them better than strong and young persons who have not been so accustomed.",
 "Old people who move every day handle hard work better than strong young people who don't.",{}),
('',"Wu Pu, student of the physician Hua Tuo · Sanguozhi, tr. from Chinese",
 "Wu Pu learned Hua Tuo's Five Animals exercise: tiger, deer, bear, ape and bird. The old history says he practised it, and at over ninety his hearing and sight were sharp and his teeth whole and firm.",
 "The old history says the student who did these animal moves stayed sharp past ninety.",{'s':1}),
('',"Galen · On Health V.4, tr. P. N. Singer, 2023",
 "Galen tells of Antiochus, a doctor past eighty, who walked daily from home to the town square and visited nearby patients on foot. Through this routine he ‘continued right to the end with his senses unimpaired and his limbs supple.’",
 "A doctor over eighty walked every day and still saw patients. His body stayed supple.",{'s':1}),
('',"Socrates · Xenophon, Symposium 2.16-19, tr. H. G. Dakyns, 1897",
 "Socrates asked to learn the dance steps, and everyone laughed. He replied: ‘Pray, do you find it so ridiculous my wishing to improve my health by exercise?...’",
 "Wanting to move more at any age is never silly. It is good for your health.",{'s':1}),
('',"Kaibara Ekiken · Yojokun, 1713 · tr. from Japanese",
 "In his eighties, finishing his health book, Kaibara Ekiken wrote: ‘Now, at eighty-three, I still write and read small characters at night; my teeth are firm and not one has fallen out.’",
 "He lived by his own advice. In his eighties he was still reading and writing at night.",{'s':1}),
('',"Russian proverb · V. I. Dal's collection, 1862",
 "Old, but sturdy. Both fresh and fit.",
 "You can be old and still strong, fresh and ready.",{}),
('',"T. Krishnamacharya · Yoga Journal, 2007",
 "In 1950, when Krishnamacharya was about 60, his yoga school in Mysore closed and he had to start over. He moved to Chennai, taught new students, healthy and sick, for decades, and turned 100 there in November 1988.",
 "At about 60 he had to start again. He kept teaching and reached 100.",{'s':1}),
('',"B. K. S. Iyengar · to Yoga Journal, 2008",
 "Even now, the maximum my body can do, I do. I am 90, and still I practice. I stay in Sirsasana (Headstand) for half an hour, even without shaking. I'm improving still, progressing still.",
 "At 90 he still practised every day and felt he was still getting better.",{}),
('',"Tao Porchon-Lynch · NBC News, 2012",
 "In 2012, aged 93, Tao Porchon-Lynch was named the world's oldest yoga teacher by Guinness World Records, still teaching four days a week. ‘I believe that we can always reach just a little bit further.’",
 "At 93 she still taught four days a week and kept reaching a little further.",{'s':1}),
('',"K. Pattabhi Jois · The Guardian, 2009",
 "The Guardian wrote of Pattabhi Jois: ‘Up every morning to start classes at 5am, he rarely missed a day's teaching in 70 years.’ He taught at his own school until 2008, into his nineties.",
 "Our Ashtanga comes from a teacher who showed up every morning for 70 years.",{'s':1}),
])
B5=('NEVER TOO LATE',[
('9-120',"Japanese proverb · Rokujū no tenarai",
 "Handwriting practice at sixty.",
 "Starting to learn at sixty is fine. It is never too late.",{}),
('',"Sawang Janpram, Thai masters athlete · Korea JoongAng Daily, Aug 2026",
 "Sawang Janpram of Thailand began exercising in earnest at 80. At 106 he won world masters gold in discus and javelin: ‘I hope that young people realize the importance of health and exercise every day.’",
 "He started at 80 and won world gold at 106.",{'s':1}),
('',"Ino Tadataka, mapmaker · Ino Tadataka Museum, Katori City",
 "At 50, Ino Tadataka moved to Edo (old Tokyo) to study astronomy with a teacher 19 years younger. From 55 to 71 his team made 10 surveys of Japan, walking about 40,000 km, roughly once around the Earth.",
 "He started a new study at 50 and walked across Japan from 55 to 71.",{'s':1}),
('',"Leo Tolstoy · Diary, 1895 and 1897, tr. from Russian",
 "At 66, Leo Tolstoy began learning to ride a bicycle in a Moscow riding hall. It ‘cheers me like a child,’ he wrote, and at 68 he rode to nearby Yasenki: ‘I love this movement very much.’",
 "Tolstoy learned to ride a bike at 66, and it made him as happy as a child.",{'s':1}),
('',"Wang Deshun · CNN Style, 2016",
 "Wang Deshun started going to the gym at 50, and at 79 walked his first runway in Beijing. ‘As long as you dare to do things you have never done before, your heart is still young.’",
 "He started getting fit at 50, and at 79 it opened a new door.",{'s':1}),
('',"Emma ‘Grandma’ Gatewood · Sports Illustrated, 1955",
 "In 1955, at 67, Emma Gatewood became the first woman to hike the whole Appalachian Trail alone. ‘I would never have started this trip if I had known how tough it was, but I couldn't and I wouldn't quit.’",
 "At 67 she hiked a very long, hard trail. It was tough, but she did not give up.",{'s':1}),
('',"Yuichiro Miura · Guinness World Records; Financial Times, 2017",
 "In his 60s, Yuichiro Miura says, he ate and drank too much and ‘grappled with diabetes’. He trained, and stood on top of Everest at 70, at 75, and in 2013 at 80 years 223 days.",
 "Unwell in his sixties, he began training and climbed Everest at 80.",{'s':1}),
('',"Mieko Nagaoka · Japan Foundation for Aging and Health, 2015",
 "At 80, fluid in her knee made Noh dance hard, so Mieko Nagaoka took to the pool as rehab: ‘It took me a year to be able to swim 25 metres.’ At 100, she swam 1,500 metres.",
 "She took up swimming at 80 to help her knee. At 100 she swam 1,500 metres.",{'s':1}),
('',"Kokichi Akuzawa · Guinness World Records, 2025",
 "After a fall, shingles and heart failure, Kokichi Akuzawa trained with hour-long walks and a mountain almost every week. In August 2025, aged 102, he topped Mount Fuji and later said: ‘It's better to climb while you still can.’",
 "At 102, after being ill, he trained by walking and climbed Mount Fuji.",{'s':1}),
])
